package migration

import (
	"context"
	"os"
	"path/filepath"

	cascadecontext "github.com/acamarata/cascade/internal/context"
	"github.com/acamarata/cascade/pkg/cascade"
)

// Purpose: one project's read-only scan — Discover+MergeTiers+Generate,
//
//	called exactly as internal/context.Sync's own checkOnly path calls
//	them (S-08/S-09), plus this package's own byte-diff (diff.go) against
//	the file already on disk. Never writes; Run (instruction_regen.go)
//	is the only place in this package that ever calls Sync's write path.
//
// Inputs: a project directory and an injectable HomeDirFunc.
// Outputs: []DriftEntry, or a typed cascade.Error for a project directory
//
//	that could not be read at all (see scanOneProject's up-front os.Stat —
//	Discover itself treats an absent tier as "nothing to report", not an
//	error, so an unreadable PROJECT directory needs its own check here to
//	surface as the "unreadable project dir" acceptance criterion rather
//	than silently reporting zero drift).
//
// Constraints: read-only filesystem access only (os.Stat, os.ReadFile).
// SPORT: internal/migration [ADD] (P1-E26-W10-S53-T3 sport_updates).

// namedGenerator pairs one harness generator with the short id this
// package's report renders, mirroring internal/context's own unexported
// harnessName switch (sync.go) — duplicated here, not imported, because
// that switch is unexported and this package must not modify
// internal/context to reach it (other tickets own those files).
type namedGenerator struct {
	name string
	gen  cascadecontext.HarnessGenerator
}

// harnessGenerators is this package's own list of the three harness
// writers, in the same order internal/context's harnessWriters() uses, so
// a project's drift entries come out in stable, deterministic order.
func harnessGenerators() []namedGenerator {
	return []namedGenerator{
		{"claude", &cascadecontext.CCInstructionWriter{}},
		{"codex", &cascadecontext.CXInstructionWriter{}},
		{"opencode", &cascadecontext.OCInstructionWriter{}},
	}
}

// scanOneProject resolves projectPath's merged context and diffs every
// harness's freshly generated file against what is on disk right now.
func scanOneProject(ctx context.Context, projectPath string, homeDir cascadecontext.HomeDirFunc) ([]DriftEntry, error) {
	info, err := os.Stat(projectPath)
	switch {
	case os.IsNotExist(err):
		return nil, cascade.Newf(cascade.KindNotFound, "migration: project directory %q does not exist", projectPath)
	case err != nil:
		return nil, cascade.Wrapf(cascade.KindUnavailable, err, "migration: project directory %q is unreadable", projectPath)
	case !info.IsDir():
		return nil, cascade.Newf(cascade.KindInvalidInput, "migration: project path %q is not a directory", projectPath)
	}

	records, err := cascadecontext.Discover(ctx, projectPath, homeDir)
	if err != nil {
		return nil, err
	}
	mc, err := cascadecontext.MergeTiers(records)
	if err != nil {
		return nil, err
	}
	roots := make(map[cascadecontext.TierRole]string, len(records))
	for _, rec := range records {
		roots[rec.Role] = rec.Dir
	}
	return driftEntriesForProject(mc, roots)
}

// driftEntriesForProject generates every harness's files for mc and
// reports the ones whose on-disk content differs. A path already reported
// by an earlier harness in this loop (the AGENTS.md pair: codex and
// opencode target the same file) is not reported twice, mirroring
// internal/context.DriftCheck's own dedup rule for the identical reason.
func driftEntriesForProject(mc cascadecontext.MergedContext, roots map[cascadecontext.TierRole]string) ([]DriftEntry, error) {
	var entries []DriftEntry
	seen := make(map[string]struct{})
	for _, ng := range harnessGenerators() {
		files, err := ng.gen.Generate(mc)
		if err != nil {
			return entries, cascade.Wrapf(cascade.KindInternal, err, "migration: generate %s instructions", ng.name)
		}
		for _, f := range files {
			root := roots[f.Role]
			if root == "" {
				continue
			}
			path := filepath.Join(root, filepath.FromSlash(f.Name))
			if _, dup := seen[path]; dup {
				continue
			}
			seen[path] = struct{}{}
			entry, stale, err := buildDriftEntry(path, f.Content)
			if err != nil {
				return entries, err
			}
			if stale {
				entries = append(entries, entry)
			}
		}
	}
	return entries, nil
}

// buildDriftEntry reads path (a missing file reads as empty content — the
// generated bytes then show entirely as additions) and diffs it against
// generated.
func buildDriftEntry(path string, generated []byte) (DriftEntry, bool, error) {
	existing, err := os.ReadFile(path) //nolint:gosec // path is composed from discovered tier roots, not user input.
	switch {
	case os.IsNotExist(err):
		existing = nil
	case err != nil:
		return DriftEntry{}, false, cascade.Wrapf(cascade.KindUnavailable, err, "migration: read %q", path)
	}
	added, removed, body := diffLines(string(existing), string(generated))
	if added == 0 && removed == 0 {
		return DriftEntry{}, false, nil
	}
	return DriftEntry{HarnessFile: path, Added: added, Removed: removed, DiffBody: body}, true, nil
}
