package context

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/acamarata/cascade/pkg/cascade"
)

// Tests for the materialization half of the generation seam: what happens
// when the target file already exists, and what never happens to a file
// somebody edited by hand.

// ccFile builds a HarnessFile carrying a freshly rendered block.
func ccFile(t *testing.T, role TierRole, heading, body string) HarnessFile {
	t.Helper()
	block := renderTierBlock(role, []MergedSection{
		{Heading: heading, Content: "## " + heading + "\n\n" + body, Role: role},
	})
	return HarnessFile{Name: ccTargetName, Content: []byte(block + "\n"), Role: role}
}

func TestWriteHarnessFileCreatesThenLeavesAlone(t *testing.T) {
	path := filepath.Join(t.TempDir(), ".claude", "CLAUDE.md")
	f := ccFile(t, TierGCI, "Style", "Short sentences.")

	first, err := WriteHarnessFile(path, f, RefuseIfEdited)
	if err != nil {
		t.Fatalf("first write: %v", err)
	}
	if first.Action != ActionCreated {
		t.Fatalf("first write action = %v, want ActionCreated", first.Action)
	}
	before, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading back: %v", err)
	}
	if string(before) != string(f.Content) {
		t.Fatal("the created file does not hold the generated bytes")
	}

	second, err := WriteHarnessFile(path, f, RefuseIfEdited)
	if err != nil {
		t.Fatalf("second write: %v", err)
	}
	if second.Action != ActionUnchanged {
		t.Fatalf("second write action = %v, want ActionUnchanged", second.Action)
	}
	after, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading back: %v", err)
	}
	if string(after) != string(before) {
		t.Fatal("regenerating over an untouched file changed its bytes")
	}
}

// TestWriteHarnessFileIdempotentAcrossManyRuns is hard requirement 2 at the
// filesystem level: repeated runs neither accumulate blocks nor reorder
// anything.
func TestWriteHarnessFileIdempotentAcrossManyRuns(t *testing.T) {
	path := filepath.Join(t.TempDir(), "CLAUDE.md")
	f := ccFile(t, TierPRI, "Tests", "Run them.")
	for i := 0; i < 10; i++ {
		if _, err := WriteHarnessFile(path, f, RefuseIfEdited); err != nil {
			t.Fatalf("run %d: %v", i, err)
		}
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading back: %v", err)
	}
	if string(got) != string(f.Content) {
		t.Fatalf("after 10 runs the file drifted:\n%s", string(got))
	}
	if n := strings.Count(string(got), markerOpenPrefix); n != 1 {
		t.Fatalf("the file carries %d managed blocks, want 1", n)
	}
}

// TestWriteHarnessFileAppendsToHandAuthoredFile pins the v1 behaviour that
// content a person wrote is never truncated to make room for generated
// content.
func TestWriteHarnessFileAppendsToHandAuthoredFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "CLAUDE.md")
	const owned = "# My own notes\n\nDo not lose this.\n"
	if err := os.WriteFile(path, []byte(owned), 0o600); err != nil {
		t.Fatalf("seeding: %v", err)
	}

	res, err := WriteHarnessFile(path, ccFile(t, TierPPI, "Style", "Short."), RefuseIfEdited)
	if err != nil {
		t.Fatalf("append: %v", err)
	}
	if res.Action != ActionAppended {
		t.Fatalf("action = %v, want ActionAppended", res.Action)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading back: %v", err)
	}
	if !strings.HasPrefix(string(got), owned) {
		t.Fatal("the hand-authored content was not preserved verbatim at the top of the file")
	}

	// A second run must replace the block in place, not append another.
	if _, err := WriteHarnessFile(path, ccFile(t, TierPPI, "Style", "Short."), RefuseIfEdited); err != nil {
		t.Fatalf("second append: %v", err)
	}
	again, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading back: %v", err)
	}
	if string(again) != string(got) {
		t.Fatalf("a second run over an appended file changed it:\n%s", string(again))
	}
}

// TestWriteHarnessFileRefusesToClobberAHandEdit is hard requirement 3. The
// default policy refuses, names the file, and leaves every byte in place.
func TestWriteHarnessFileRefusesToClobberAHandEdit(t *testing.T) {
	path := filepath.Join(t.TempDir(), "CLAUDE.md")
	f := ccFile(t, TierGCI, "Style", "Short sentences.")
	if _, err := WriteHarnessFile(path, f, RefuseIfEdited); err != nil {
		t.Fatalf("seeding: %v", err)
	}
	edited := strings.Replace(string(f.Content), "Short sentences.", "Edited by hand.", 1)
	if err := os.WriteFile(path, []byte(edited), 0o600); err != nil {
		t.Fatalf("planting the edit: %v", err)
	}

	res, err := WriteHarnessFile(path, f, RefuseIfEdited)
	if err == nil {
		t.Fatal("a hand-edited managed block was overwritten without a word")
	}
	var ce *cascade.Error
	if !errors.As(err, &ce) || ce.Kind != cascade.KindConflict {
		t.Fatalf("error = %v, want a KindConflict taxonomy error", err)
	}
	if !strings.Contains(err.Error(), path) {
		t.Errorf("the refusal does not name the file: %v", err)
	}
	if res.Action != ActionUnchanged || res.Path != "" {
		t.Errorf("a refused write returned a non-zero result: %+v", res)
	}
	still, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading back: %v", err)
	}
	if string(still) != edited {
		t.Fatal("the refused write still modified the file")
	}
}

// TestWriteHarnessFileBacksUpAHandEdit is the other half of requirement 3:
// the caller may choose to overwrite, and the overwrite is announced with
// the preserved copy's path.
func TestWriteHarnessFileBacksUpAHandEdit(t *testing.T) {
	path := filepath.Join(t.TempDir(), "CLAUDE.md")
	f := ccFile(t, TierGCI, "Style", "Short sentences.")
	if _, err := WriteHarnessFile(path, f, BackupIfEdited); err != nil {
		t.Fatalf("seeding: %v", err)
	}
	edited := strings.Replace(string(f.Content), "Short sentences.", "Edited by hand.", 1)
	if err := os.WriteFile(path, []byte(edited), 0o600); err != nil {
		t.Fatalf("planting the edit: %v", err)
	}

	res, err := WriteHarnessFile(path, f, BackupIfEdited)
	if err != nil {
		t.Fatalf("backup write: %v", err)
	}
	if res.Action != ActionBackedUp {
		t.Fatalf("action = %v, want ActionBackedUp", res.Action)
	}
	if res.BackupPath == "" {
		t.Fatal("an overwrite happened with no backup path reported")
	}
	saved, err := os.ReadFile(res.BackupPath)
	if err != nil {
		t.Fatalf("reading the backup: %v", err)
	}
	if string(saved) != edited {
		t.Fatal("the backup does not hold the user's edit")
	}
	now, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading back: %v", err)
	}
	if string(now) != string(f.Content) {
		t.Fatal("the regenerated file does not hold the generated bytes")
	}
}

// TestManagedBlockWithoutDigestIsTreatedAsIntact covers the v1-written file:
// its marker carries no digest, and refusing to touch it would strand the
// users an upgrade exists to serve.
func TestManagedBlockWithoutDigestIsTreatedAsIntact(t *testing.T) {
	path := filepath.Join(t.TempDir(), "CLAUDE.md")
	legacy := markerOpenPrefix + " -->\n## Cascade Context\n\nold text\n" + markerClose + "\n"
	if err := os.WriteFile(path, []byte(legacy), 0o600); err != nil {
		t.Fatalf("seeding: %v", err)
	}
	f := ccFile(t, TierGCI, "Style", "Short sentences.")
	res, err := WriteHarnessFile(path, f, RefuseIfEdited)
	if err != nil {
		t.Fatalf("upgrading a v1-written file: %v", err)
	}
	if res.Action != ActionUpdated {
		t.Fatalf("action = %v, want ActionUpdated", res.Action)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading back: %v", err)
	}
	if strings.Contains(string(got), "old text") {
		t.Error("the replaced block's content survived the update")
	}
}

// TestGenerateCCInstructionsDrivesTheRealPipeline exercises the production
// entry point end to end against a real directory tree, so discovery, merge,
// render and write are proven to be connected rather than merely present.
func TestGenerateCCInstructionsDrivesTheRealPipeline(t *testing.T) {
	root := t.TempDir()
	home := filepath.Join(root, "home")
	repo := filepath.Join(home, "sites", "project", "repo")
	seedTier(t, home, "## Style\n\nShort sentences.\n")
	seedTier(t, repo, "## Style\n\nLong sentences.\n\n## Tests\n\nRun them.\n")

	homeFn := func() (string, error) { return home, nil }
	results, err := GenerateCCInstructions(context.Background(), repo, homeFn, RefuseIfEdited)
	if err != nil {
		t.Fatalf("pipeline: %v", err)
	}
	if len(results) != 2 {
		t.Fatalf("got %d results, want 2 (GCI and PRI)", len(results))
	}
	gci, err := os.ReadFile(filepath.Join(home, ".claude", "CLAUDE.md"))
	if err != nil {
		t.Fatalf("reading the GCI file: %v", err)
	}
	if !strings.Contains(string(gci), "Short sentences.") {
		t.Error("the GCI file does not carry the GCI tier's own text")
	}
	pri, err := os.ReadFile(filepath.Join(repo, ".claude", "CLAUDE.md"))
	if err != nil {
		t.Fatalf("reading the PRI file: %v", err)
	}
	if strings.Contains(string(pri), "Long sentences.") {
		t.Error("the PRI file carries a section the higher tier won")
	}
	if !strings.Contains(string(pri), "Run them.") {
		t.Error("the PRI file lost the section no higher tier defined")
	}

	// Second run over the same tree must change nothing at all.
	again, err := GenerateCCInstructions(context.Background(), repo, homeFn, RefuseIfEdited)
	if err != nil {
		t.Fatalf("second pipeline run: %v", err)
	}
	for _, r := range again {
		if r.Action != ActionUnchanged {
			t.Errorf("%s: action = %v on a repeat run, want ActionUnchanged", r.Path, r.Action)
		}
	}
}

// seedTier writes a cascade tier instruction file under dir.
func seedTier(t *testing.T, dir, content string) {
	t.Helper()
	full := filepath.Join(dir, tierDirName)
	if err := os.MkdirAll(full, 0o755); err != nil {
		t.Fatalf("seeding %s: %v", full, err)
	}
	if err := os.WriteFile(filepath.Join(full, tierFileName), []byte(content), 0o600); err != nil {
		t.Fatalf("seeding %s: %v", full, err)
	}
}
