//! cascade-pdk — Plugin Development Kit for Cascade WASM plugins.
//!
//! # Purpose
//! Provides the guest-side counterpart to the host's WIT bindings in
//! `cascade-plugins`. Plugin authors add this crate as a dependency,
//! implement the [`Plugin`] trait on their struct, apply the
//! [`macro@cascade_plugin`] attribute, and compile with
//! `--target wasm32-wasip1`.
//!
//! # JSON-string ABI
//! The Cascade host communicates with WASM guests via a JSON-string ABI:
//! - Every call is serialised to a JSON UTF-8 string.
//! - The guest receives a pointer + length pair referencing host-owned memory.
//! - The guest returns a pointer + length pair to guest-owned memory.
//! - Memory is managed via the exported `alloc` / `dealloc` pair below.
//!
//! # Architecture
//! ```text
//! Host (cascade-plugins) --- JSON bytes ---> guest WASM
//!   call_export_json()                        cascade_plugin_call()
//!                      <--- JSON bytes ---
//! ```
//!
//! # Target notes
//! `wasm32-wasip1` is a full WASI target — std is available.
//! `no_std` is NOT used; std is the correct choice here.
//!
//! # Usage example
//! ```rust,ignore
//! use cascade_pdk::{cascade_plugin, Plugin, PluginKind, ToolCall, ToolResult, PluginError};
//!
//! #[cascade_plugin]
//! pub struct MyTool;
//!
//! impl Plugin for MyTool {
//!     fn name(&self) -> &str { "my-tool" }
//!     fn kind(&self) -> PluginKind { PluginKind::ChatTool }
//!
//!     fn on_tool_call(&self, call: ToolCall) -> Result<ToolResult, PluginError> {
//!         Ok(ToolResult {
//!             call_id: call.call_id,
//!             output: format!("Hello from my-tool: {}", call.args_json),
//!             data_json: None,
//!         })
//!     }
//! }
//! ```
//!
//! Inputs:  cascade-plugins host WIT ABI (JSON-string encoding)
//! Outputs: serde-serialised return values through the ABI
//! Constraints: no std::fs, std::net, or std::thread in this crate
//! SPORT: cascade-pdk crate (T-P4-E03-10)

pub use cascade_pdk_macro::{
    cascade_plugin, register_agent, register_chunker, register_provider, register_retriever,
    register_tool,
};

pub mod dispatch;
pub mod host_imports;
pub mod plugin;
pub mod types;

#[cfg(all(feature = "test-harness", not(target_arch = "wasm32")))]
pub mod test_harness;

/// Private module re-exported for use by `#[cascade_plugin]`-generated code.
/// Not part of the public API — may change without notice.
#[doc(hidden)]
pub mod __private {
    pub use crate::dispatch::{dispatch, error_json, DispatchEnvelope};
    pub use serde_json;

    pub type String = ::std::string::String;
}

pub use plugin::Plugin;
pub use types::{
    AgentContext, AgentResponse, Chunk, ChunkMeta, ChunkOpts, ContextEntry, DataItem,
    DataSourceFetchArgs, DataSourcePage, Document, EmbedOpts, Embedding, PluginError, PluginKind,
    RetrievalResult, RetrieveOpts, ToolCall, ToolResult, WidgetData,
};

// ── WASM memory management exports ───────────────────────────────────────────
// The host uses these to allocate/free memory when passing JSON strings in.
// Only compiled for wasm32 targets — on host they are unused.

/// Allocate `len` bytes and return the pointer.
///
/// The host calls this before writing a JSON argument string into guest memory.
/// On wasm32-wasip1 std is available so we use the standard allocator directly.
#[cfg(target_arch = "wasm32")]
#[no_mangle]
pub extern "C" fn alloc(len: usize) -> *mut u8 {
    let layout = std::alloc::Layout::array::<u8>(len).expect("layout");
    // Safety: layout is valid (non-zero size, aligned for u8).
    unsafe { std::alloc::alloc(layout) }
}

/// Free a slice of memory previously allocated by [`alloc`].
///
/// Called by the host after it has read the guest's return value.
#[cfg(target_arch = "wasm32")]
#[no_mangle]
pub extern "C" fn dealloc(ptr: *mut u8, len: usize) {
    if len == 0 {
        return;
    }
    let layout = std::alloc::Layout::array::<u8>(len).expect("layout");
    // Safety: ptr was returned by alloc() with the same len.
    unsafe { std::alloc::dealloc(ptr, layout) }
}

// Plugin entry point `cascade_plugin_call` is generated by the
// `#[cascade_plugin]` proc-macro on the concrete plugin struct.  It is NOT
// declared here — the macro emits the real `#[no_mangle] pub extern "C" fn`
// in the plugin crate.  See `cascade-pdk-macro` for the generated code.
