//! # lint_behavioral — behavioral-core rule presence checker
//!
//! Verifies that generated harness files (CLAUDE.md / AGENTS.md) include
//! all behavioral-core rule headings that Cascade ships as always-loaded
//! defaults.
//!
//! ## Purpose
//!
//! Starting with v1.4, `compat_gen` embeds behavioral-core rule content
//! inline in generated harness files.  When a generated file is missing one
//! or more of the expected H1 headings it means either:
//!
//! - The file was generated by an older Cascade version that did not embed
//!   behavioral rules, or
//! - The headings were stripped after generation.
//!
//! This module surfaces those situations so `cascade doctor` can report them.
//!
//! ## Detection heuristic
//!
//! For each `CLAUDE.md` / `AGENTS.md` found under the supplied scan dirs:
//!
//! 1. Check whether the first line starts with [`GENERATED_MARKER`].  Files
//!    that are NOT generated are skipped with no finding.
//! 2. For generated files, test whether ALL [`BEHAVIORAL_CORE_HEADINGS`] are
//!    present anywhere in the file content.
//! 3. Return one [`BehavioralCoreFinding`] per file that is missing at least
//!    one heading, listing all missing headings for that file.
//!
//! ## Inputs / Outputs
//!
//! - **Input:** `scan_dirs: &[PathBuf]` — directories to check (typically the
//!   `cascade_dir` values from resolved tier results).
//! - **Output:** `Vec<BehavioralCoreFinding>` — one entry per generated file
//!   with missing behavioral-core headings; empty when all headings are present.
//!
//! ## Constraints
//!
//! - Read-only: no files are written or modified.
//! - No `unwrap()` outside `#[cfg(test)]` blocks.
//! - Files that cannot be read are silently skipped (no finding, no panic).
//!
//! ## SPORT
//!
//! MASTER-CRATES.md — cascade-core: lint_behavioral module (P12-behavioral-layer)

use std::path::PathBuf;

use crate::compat_gen::GENERATED_MARKER;

// ── Constants ─────────────────────────────────────────────────────────────────

/// The canonical set of H1 headings that every v1.4+ generated harness file
/// must contain.  One per always-loaded behavioral-core rule.
const BEHAVIORAL_CORE_HEADINGS: &[&str] = &[
    "# Anti-Drift",
    "# Autonomous Verification",
    "# Dynamic Learning",
    "# Authorization and Autonomy",
    "# Vision and Mission Discipline",
    "# Delegation and Model Discipline",
    "# Security",
];

/// File names that `compat_gen` may generate inside a tier directory.
const GENERATED_FILENAMES: &[&str] = &["CLAUDE.md", "AGENTS.md"];

// ── Public types ──────────────────────────────────────────────────────────────

/// A single behavioral-core heading drift finding.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BehavioralCoreFinding {
    /// Absolute path to the generated file with missing headings.
    pub path: PathBuf,
    /// The behavioral-core headings absent from this file.
    pub missing_headings: Vec<String>,
}

// ── Entry point ───────────────────────────────────────────────────────────────

/// Scan `scan_dirs` for generated cascade files that are missing behavioral-core
/// rule headings.
///
/// Only files that carry the [`GENERATED_MARKER`] on their first line are
/// checked.  Non-generated files are silently skipped.
///
/// # Arguments
///
/// * `scan_dirs` — directories to scan (typically the `cascade_dir` values
///   from resolved tier results).
///
/// # Returns
///
/// `Vec<BehavioralCoreFinding>` — empty when all generated files contain all
/// behavioral-core headings, or when no generated files are found.
pub fn lint_behavioral_core(scan_dirs: &[PathBuf]) -> Vec<BehavioralCoreFinding> {
    let mut findings = Vec::new();

    for dir in scan_dirs {
        for &filename in GENERATED_FILENAMES {
            let path = dir.join(filename);
            if !path.is_file() {
                continue;
            }
            if let Some(finding) = check_behavioral_file(&path) {
                findings.push(finding);
            }
        }
    }

    findings
}

// ── File-level check ──────────────────────────────────────────────────────────

/// Check a single file for missing behavioral-core headings.
///
/// Returns `None` when:
/// - The file cannot be read (silently skipped).
/// - The file is not generated (no [`GENERATED_MARKER`] on line 1).
/// - All behavioral-core headings are present.
///
/// Returns `Some(BehavioralCoreFinding)` when the file is generated and is
/// missing at least one heading.
fn check_behavioral_file(path: &std::path::Path) -> Option<BehavioralCoreFinding> {
    let content = std::fs::read_to_string(path).ok()?;

    // Only inspect files that carry the generated marker.
    let first_line = content.lines().next().unwrap_or("");
    if !first_line.starts_with(GENERATED_MARKER) {
        return None;
    }

    // Collect any headings that are absent.
    let missing: Vec<String> = BEHAVIORAL_CORE_HEADINGS
        .iter()
        .filter(|&&heading| !content.contains(heading))
        .map(|&h| h.to_owned())
        .collect();

    if missing.is_empty() {
        None
    } else {
        Some(BehavioralCoreFinding {
            path: path.to_path_buf(),
            missing_headings: missing,
        })
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    /// Build a generated file content string with the given extra body appended.
    fn generated_content(extra: &str) -> String {
        format!("{GENERATED_MARKER}\n{extra}")
    }

    /// Build a string containing all behavioral-core headings.
    fn all_headings() -> String {
        BEHAVIORAL_CORE_HEADINGS
            .iter()
            .map(|h| format!("{h}\n\nSome rule content.\n\n"))
            .collect()
    }

    // ── Test 1: generated file with all headings → no finding ────────────────

    /// A generated file that contains all headings produces no finding.
    ///
    /// WHY: happy path; correctly generated v1.4+ files must not be flagged.
    #[test]
    fn generated_file_with_all_headings_no_finding() {
        let tmp = TempDir::new().unwrap();
        let content = generated_content(&all_headings());
        fs::write(tmp.path().join("CLAUDE.md"), content).unwrap();

        let findings = lint_behavioral_core(&[tmp.path().to_path_buf()]);
        assert!(
            findings.is_empty(),
            "no finding expected when all headings present: {findings:#?}"
        );
    }

    // ── Test 2: generated file missing one heading → one finding ─────────────

    /// A generated file missing exactly one heading reports that one heading.
    ///
    /// WHY: core contract — each missing heading must be reported precisely.
    #[test]
    fn generated_file_missing_one_heading_reports_it() {
        let tmp = TempDir::new().unwrap();
        // Include all headings except "# Dynamic Learning".
        let headings: String = BEHAVIORAL_CORE_HEADINGS
            .iter()
            .filter(|&&h| h != "# Dynamic Learning")
            .map(|h| format!("{h}\n\nSome rule content.\n\n"))
            .collect();
        let content = generated_content(&headings);
        let path = tmp.path().join("CLAUDE.md");
        fs::write(&path, content).unwrap();

        let findings = lint_behavioral_core(&[tmp.path().to_path_buf()]);
        assert_eq!(findings.len(), 1, "expected exactly one finding");
        assert_eq!(findings[0].path, path);
        assert_eq!(findings[0].missing_headings, vec!["# Dynamic Learning"]);
    }

    // ── Test 3: non-generated file → ignored ──────────────────────────────────

    /// A CLAUDE.md without the generated marker is not inspected, even if
    /// all behavioral-core headings are absent.
    ///
    /// WHY: hand-written harness files must not be flagged.
    #[test]
    fn non_generated_file_ignored() {
        let tmp = TempDir::new().unwrap();
        let content = "# My hand-written instructions\nNo headings here.\n";
        fs::write(tmp.path().join("CLAUDE.md"), content).unwrap();

        let findings = lint_behavioral_core(&[tmp.path().to_path_buf()]);
        assert!(
            findings.is_empty(),
            "non-generated file must not produce a finding: {findings:#?}"
        );
    }

    // ── Test 4: generated file missing all headings → one finding with all ───

    /// A generated file with only the marker and no headings produces one
    /// finding that lists all missing headings.
    ///
    /// WHY: verifies the full-miss case and that all headings are tracked.
    #[test]
    fn generated_file_missing_all_headings_reports_all() {
        let tmp = TempDir::new().unwrap();
        let content = generated_content("No headings here at all.\n");
        let path = tmp.path().join("CLAUDE.md");
        fs::write(&path, content).unwrap();

        let findings = lint_behavioral_core(&[tmp.path().to_path_buf()]);
        assert_eq!(findings.len(), 1, "expected exactly one finding");
        assert_eq!(findings[0].path, path);
        assert_eq!(
            findings[0].missing_headings.len(),
            BEHAVIORAL_CORE_HEADINGS.len(),
            "all headings must be reported missing"
        );
        for heading in BEHAVIORAL_CORE_HEADINGS {
            assert!(
                findings[0].missing_headings.contains(&heading.to_string()),
                "missing heading not reported: {heading}"
            );
        }
    }

    // ── Test 5b: # Security heading is required ───────────────────────────────

    /// A generated file missing only "# Security" reports exactly that heading.
    ///
    /// WHY: verifies the new always-loaded behavioral-core rule is tracked.
    #[test]
    fn generated_file_missing_security_heading_reports_it() {
        let tmp = TempDir::new().unwrap();
        let headings: String = BEHAVIORAL_CORE_HEADINGS
            .iter()
            .filter(|&&h| h != "# Security")
            .map(|h| format!("{h}\n\nSome rule content.\n\n"))
            .collect();
        let content = generated_content(&headings);
        let path = tmp.path().join("CLAUDE.md");
        fs::write(&path, content).unwrap();

        let findings = lint_behavioral_core(&[tmp.path().to_path_buf()]);
        assert_eq!(findings.len(), 1, "expected exactly one finding");
        assert_eq!(findings[0].missing_headings, vec!["# Security"]);
    }

    // ── Test 5: empty scan_dirs → empty result ────────────────────────────────

    /// Passing an empty slice of scan dirs returns an empty findings vec.
    ///
    /// WHY: callers with no tier dirs must not panic or produce spurious output.
    #[test]
    fn empty_scan_dirs_returns_empty() {
        let findings = lint_behavioral_core(&[]);
        assert!(findings.is_empty(), "empty dirs must return empty findings");
    }
}
