//! # lint_generated — hand-edited generated-file detector
//!
//! Detects cascade-managed harness files (files marked with [`GENERATED_MARKER`])
//! that have been modified by hand after generation.
//!
//! ## Purpose
//!
//! `cascade compat-gen` writes `CLAUDE.md` / `AGENTS.md` files at each tier
//! directory and stamps them with a stable first-line marker.  When a user
//! edits such a file the next `cascade resolve` call will silently overwrite
//! their changes.  This module surfaces those situations before they cause
//! surprises.
//!
//! ## Detection heuristic
//!
//! A file is considered "hand-edited" when ALL of the following hold:
//!
//! 1. The first line equals [`GENERATED_MARKER`].
//! 2. The file contains a content-hash comment of the form
//!    `<!-- cascade:content-hash: <hex> -->`.
//! 3. The SHA-256 of the file body (everything after the hash comment line)
//!    does NOT match the stored hex value.
//!
//! When a generated file does NOT embed a content hash, the check is skipped
//! with no finding (a best-effort WARN is still emitted if the caller enables
//! `tracing`).  This avoids false positives for files generated by older
//! versions of `compat_gen`.
//!
//! ## Inputs / Outputs
//!
//! - **Input:** `scan_dirs: &[PathBuf]` — a list of directories to check for
//!   `CLAUDE.md` / `AGENTS.md`.  Callers pass the `path_searched` values from
//!   resolved tiers.
//! - **Output:** `Vec<GeneratedFinding>` — one entry per hand-edited file;
//!   empty when all generated files are intact.
//!
//! ## Constraints
//!
//! - Read-only: no files are written or repaired.
//! - No `unwrap()` outside `#[cfg(test)]` blocks.
//! - The [`GENERATED_MARKER`] constant is re-exported from [`crate::compat_gen`]
//!   to keep it a single source of truth.
//!
//! ## SPORT
//!
//! MASTER-CRATES.md — cascade-core: lint_generated module (P12-doctor-drift)

use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

use crate::compat_gen::GENERATED_MARKER;

// ── Constants ─────────────────────────────────────────────────────────────────

/// Comment format used by `compat_gen` to embed a content hash in generated files.
///
/// The hash is a lower-hex SHA-256 of the file body after (and excluding) this
/// comment line.  This constant is the full prefix; the hex value follows.
pub const HASH_COMMENT_PREFIX: &str = "<!-- cascade:content-hash: ";

/// File names that `compat_gen` may generate inside a tier directory.
const GENERATED_FILENAMES: &[&str] = &["CLAUDE.md", "AGENTS.md"];

// ── Public types ──────────────────────────────────────────────────────────────

/// A single hand-edited generated-file finding.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFinding {
    /// Absolute path to the file that appears hand-edited.
    pub path: PathBuf,
    /// The hash stored in the file (what was expected).
    pub stored_hash: String,
    /// The hash computed from the current file body.
    pub actual_hash: String,
}

// ── Entry point ───────────────────────────────────────────────────────────────

/// Scan `scan_dirs` for generated cascade files that appear hand-edited.
///
/// For each directory, checks [`GENERATED_FILENAMES`] that carry the
/// [`GENERATED_MARKER`] and a content-hash comment.  Returns a finding for
/// every file whose body hash no longer matches the stored hash.
///
/// # Arguments
///
/// * `scan_dirs` — directories to scan (typically the `path_searched` values
///   from found tier results).
///
/// # Returns
///
/// `Vec<GeneratedFinding>` — empty when all generated files are intact or when
/// no generated files with embedded hashes are found.
pub fn lint_generated(scan_dirs: &[PathBuf]) -> Vec<GeneratedFinding> {
    let mut findings = Vec::new();

    for dir in scan_dirs {
        for &filename in GENERATED_FILENAMES {
            let path = dir.join(filename);
            if !path.is_file() {
                continue;
            }
            if let Some(finding) = check_generated_file(&path) {
                findings.push(finding);
            }
        }
    }

    findings
}

// ── File-level check ──────────────────────────────────────────────────────────

/// Check a single file and return a finding if it appears hand-edited.
///
/// Returns `None` when the file has no marker, has no hash comment (older
/// generated file — no finding), or when the hash matches.
fn check_generated_file(path: &Path) -> Option<GeneratedFinding> {
    let content = std::fs::read_to_string(path).ok()?;

    // 1. First line must carry the generated marker.
    let first_line = content.lines().next().unwrap_or("");
    if !first_line.starts_with(GENERATED_MARKER) {
        return None;
    }

    // 2. Find the hash comment line.
    let (stored_hash, body) = extract_hash_and_body(&content)?;

    // 3. Compute the SHA-256 of the body.
    let actual_hash = sha256_hex(body);

    // 4. Compare.
    if actual_hash == stored_hash {
        None
    } else {
        Some(GeneratedFinding {
            path: path.to_path_buf(),
            stored_hash,
            actual_hash,
        })
    }
}

/// Extract the stored hex hash and the body text (everything after the hash
/// comment line) from a generated file's content.
///
/// Returns `None` when no hash comment is present (older generated file).
fn extract_hash_and_body(content: &str) -> Option<(String, &str)> {
    // Find the line containing the hash comment.
    let hash_line_pos = content
        .lines()
        .enumerate()
        .find_map(|(i, line)| {
            if line.starts_with(HASH_COMMENT_PREFIX) {
                Some(i)
            } else {
                None
            }
        })?;

    // Extract the hex from that line.
    // Line format: `<!-- cascade:content-hash: <hex> -->`
    let hash_line = content.lines().nth(hash_line_pos)?;
    let after_prefix = hash_line.strip_prefix(HASH_COMMENT_PREFIX)?;
    let stored_hash = after_prefix.trim_end_matches(" -->").trim().to_owned();
    if stored_hash.is_empty() {
        return None;
    }

    // The body is everything in `content` after the hash-comment line.
    // We work on byte offsets to avoid re-scanning.
    let body_start = byte_offset_after_line(content, hash_line_pos);
    let body = &content[body_start..];

    Some((stored_hash, body))
}

/// Compute the SHA-256 of `text` and return it as a lower-hex string.
fn sha256_hex(text: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(text.as_bytes());
    format!("{:x}", hasher.finalize())
}

/// Return the byte offset of the first character of the line AFTER line index
/// `target_line` (0-based).  Returns `content.len()` if `target_line` is the
/// last line.
fn byte_offset_after_line(content: &str, target_line: usize) -> usize {
    let mut current_line = 0;
    for (i, ch) in content.char_indices() {
        if current_line == target_line && ch == '\n' {
            return i + 1;
        }
        if ch == '\n' {
            current_line += 1;
        }
    }
    content.len()
}

// ── Public helper for compat_gen to embed hashes ──────────────────────────────

/// Build a content-hash comment line for the given body text.
///
/// `compat_gen` should call this when generating the body of a `CLAUDE.md` and
/// embed the returned line immediately before the body content.  The [`lint_generated`]
/// check will then be able to detect if the body is subsequently modified.
///
/// # Example
///
/// ```
/// use cascade_core::lint_generated::make_hash_comment;
/// let body = "# Instructions\n...";
/// let line = make_hash_comment(body);
/// assert!(line.starts_with("<!-- cascade:content-hash:"));
/// ```
pub fn make_hash_comment(body: &str) -> String {
    format!("{}{} -->", HASH_COMMENT_PREFIX, sha256_hex(body))
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    /// Write a generated CLAUDE.md with an embedded content hash into `dir`.
    fn write_generated_file(dir: &Path, body: &str) {
        let hash_comment = make_hash_comment(body);
        let content = format!("{GENERATED_MARKER}\n{hash_comment}\n{body}");
        fs::write(dir.join("CLAUDE.md"), content).unwrap();
    }

    // ── Test 1: intact generated file → no finding ───────────────────────────

    /// A generated file whose hash still matches produces no finding.
    ///
    /// WHY: happy path; must not generate false positives on unmodified files.
    #[test]
    fn intact_generated_file_no_finding() {
        let tmp = TempDir::new().unwrap();
        let body = "# Instructions\nThis is the generated content.\n";
        write_generated_file(tmp.path(), body);

        let findings = lint_generated(&[tmp.path().to_path_buf()]);
        assert!(
            findings.is_empty(),
            "intact generated file must not produce a finding: {findings:#?}"
        );
    }

    // ── Test 2: hand-edited file → one finding ────────────────────────────────

    /// A generated file modified after generation produces exactly one finding.
    ///
    /// WHY: core contract — hand-edited generated files must be detected.
    #[test]
    fn hand_edited_file_produces_finding() {
        let tmp = TempDir::new().unwrap();
        let body = "# Instructions\nThis is the generated content.\n";
        write_generated_file(tmp.path(), body);

        // Simulate a hand edit by appending a line to the file.
        let path = tmp.path().join("CLAUDE.md");
        let mut content = fs::read_to_string(&path).unwrap();
        content.push_str("# Hand-added section\n");
        fs::write(&path, content).unwrap();

        let findings = lint_generated(&[tmp.path().to_path_buf()]);
        assert_eq!(findings.len(), 1, "must detect one hand-edited file");
        assert_eq!(findings[0].path, path);
        assert_ne!(
            findings[0].stored_hash, findings[0].actual_hash,
            "hashes must differ"
        );
    }

    // ── Test 3: file without marker → ignored ─────────────────────────────────

    /// A CLAUDE.md whose first line is NOT the generated marker is skipped.
    ///
    /// WHY: hand-written CLAUDE.md files in tier dirs must not be flagged.
    #[test]
    fn non_generated_file_ignored() {
        let tmp = TempDir::new().unwrap();
        let content = "# My custom instructions\nThis file is hand-written.\n";
        fs::write(tmp.path().join("CLAUDE.md"), content).unwrap();

        let findings = lint_generated(&[tmp.path().to_path_buf()]);
        assert!(
            findings.is_empty(),
            "hand-written CLAUDE.md must not be flagged: {findings:#?}"
        );
    }

    // ── Test 4: generated file without hash comment → no finding ─────────────

    /// A generated file that has the marker but no hash comment is silently skipped.
    ///
    /// WHY: older compat_gen versions did not embed hashes; those files must
    /// not generate false positives.
    #[test]
    fn generated_file_without_hash_not_flagged() {
        let tmp = TempDir::new().unwrap();
        // Marker present; no hash comment.
        let content = format!("{GENERATED_MARKER}\n# Instructions\nSome content.\n");
        fs::write(tmp.path().join("CLAUDE.md"), content).unwrap();

        let findings = lint_generated(&[tmp.path().to_path_buf()]);
        assert!(
            findings.is_empty(),
            "generated file without hash must not be flagged: {findings:#?}"
        );
    }

    // ── Test 5: make_hash_comment round-trips correctly ───────────────────────

    /// The hash embedded by `make_hash_comment` matches `sha256_hex` of the body.
    ///
    /// WHY: the public helper must produce a hash that the detector can verify.
    #[test]
    fn make_hash_comment_round_trips() {
        let body = "body content line 1\nbody content line 2\n";
        let comment = make_hash_comment(body);
        assert!(comment.starts_with(HASH_COMMENT_PREFIX), "wrong prefix");
        let stored = comment
            .strip_prefix(HASH_COMMENT_PREFIX)
            .unwrap()
            .trim_end_matches(" -->")
            .trim();
        assert_eq!(stored, sha256_hex(body), "stored hash must match body hash");
    }
}
