package journal

// Purpose: the provider.Store-backed Store. Append allocates each
//
//	entity's next sequence number and commits the sealed entry inside one
//	write-executor transaction (B/S-02.T2). The torn-tail recovery scan
//	R-21.216 requires (recoverEntityLocked and its helpers) lives in
//	entry.go under R-14.117's authorized-split allowance (Art.10.3's
//	300-line-per-file cap) — see that file's doc comment.
//
// Inputs: a pkg/provider.Store (the SQLite driver routes every write
//
//	through its single write-connection executor and per-domain fairness
//	queue) and an injected runtime.Clock.
//
// Outputs: sealed Entry values, or a pkg/cascade taxonomy error.
//
// CONTRACT DEVIATION (naming, recorded, not papered over). The contract's
// task text names the struct "JournalEntry" and the interface
// "JournalStore". golangci-lint's revive analyzer (the CI lint wall this
// ticket must pass with zero exceptions) flags both as stuttering exported
// names once qualified from outside the package (journal.JournalEntry,
// journal.JournalStore) and refuses them. This package therefore exports
// Entry and Store instead, and names the concrete SQLite-backed
// implementation SQLiteStore so it does not collide with the Store
// interface name. Every field, method, and JSON tag the contract specifies
// is unchanged; only the two exported type names differ from the contract
// text.
//
// CONTRACT DEVIATION (domain registration, recorded, not papered over).
// The contract also says the
// journal domain is "registered in the B/S-03.T1 cascade.db domain layout
// using the existing domain-ownership registry" as if a twelfth DomainID
// were being added. R-14.5's domain set is CLOSED at eleven (R-16.51
// amended it once, to add `policy`) and adding a twelfth is a T0 amendment
// this ticket does not have standing to make. DomainSessions is already
// documented as owned by "internal/fleet (sessions, nodes, lanes)"
// (internal/storage/domains.go) — the exact entity classes this package's
// own full_desc names ("tasks, sessions, agents"). This package therefore
// persists under DefaultNamespace = string(storage.DomainSessions), the
// existing fleet domain, and this file's change to domains.go only
// extends that domain's OwnerPkg comment to name journal explicitly. See
// the journal for both sides quoted, exactly as internal/audit/record.go's
// own CONTRACT DEVIATION note does for the identical "no new DomainID"
// situation.
//
// Recovery scope: "on open, the store scans backwards from the tail" is
// written for a single physical log file. This package's storage is a
// namespaced key-value table shared across every entity, so recoverEntity
// runs the equivalent check per entity, lazily, the first time that
// entity is touched through a given SQLiteStore instance (Append, Replay, or an
// explicit Recover call) rather than eagerly for every entity at
// construction time — there is no way to enumerate "every entity this
// SQLiteStore will ever see" up front. Within one entity's log, the scan is
// forward (lowest sequence first) rather than backward, because the two
// directions agree exactly when corruption is confined to the tail:
// Append writes each entry and its head pointer inside the same
// transaction (commitEntryTx), so a genuinely torn write from this
// package's own code is impossible — SQLite's transaction atomicity
// already prevents it. The scan instead defends against external
// corruption (bit rot, a manually damaged file), which is exactly what
// this ticket's crash-injection tests simulate by writing malformed bytes
// directly to the store, bypassing Append.
//
// SPORT: internal.fleet.journal.Store/ADDED (P1-E13-W3-S27-T1).

import (
	"context"
	"encoding/json"
	"fmt"
	"sync"

	"github.com/acamarata/cascade/internal/runtime"
	"github.com/acamarata/cascade/internal/storage"
	"github.com/acamarata/cascade/pkg/cascade"
	"github.com/acamarata/cascade/pkg/provider"
)

// DefaultNamespace is the provider.Store namespace journal entries persist
// under. See this file's CONTRACT DEVIATION note above.
const DefaultNamespace = string(storage.DomainSessions)

// keyDelim separates a key's entity id from its fixed prefix and suffix.
// It is a control byte that cannot appear in a well-formed entity id typed
// or generated by any caller in this codebase, so an entity id containing
// ordinary characters (including ':') can never be mistaken for a
// different, longer entity id's prefix.
const keyDelim = "\x00"

// seqDigits zero-pads a sequence number wide enough that lexical key order
// equals numeric order for every uint64 (max uint64 has 20 digits).
const seqDigits = 20

func entryKey(entityID string, seq uint64) string {
	return fmt.Sprintf("e:%s%s%0*d", entityID, keyDelim, seqDigits, seq)
}

func headKey(entityID string) string { return "h:" + entityID + keyDelim }

// headRecord is the per-entity tail pointer Append and recovery maintain.
type headRecord struct {
	Seq uint64 `json:"seq"`
}

// getter is the read-only subset both provider.Store and provider.Tx
// satisfy, letting loadHeadFrom and loadCheckpointFrom (checkpoint.go)
// read consistently whether called at top level or inside a transaction.
type getter interface {
	Get(ctx context.Context, namespace, key string) ([]byte, error)
}

// SQLiteStore is the provider.Store-backed Store implementation. The zero
// value is not usable; construct with New.
type SQLiteStore struct {
	store     provider.Store
	clock     runtime.Clock
	namespace string

	mu          sync.Mutex
	recovered   map[string]TruncationReport
	entityLocks sync.Map // map[string]*sync.Mutex, one per entity ID
}

// New returns a SQLiteStore persisting through store under namespace (pass
// DefaultNamespace unless a caller has a documented reason not to) and
// stamping every entry from clock. Pass runtime.NewSystemClock() in
// production and a frozen clock in tests.
func New(store provider.Store, clock runtime.Clock, namespace string) *SQLiteStore {
	return &SQLiteStore{store: store, clock: clock, namespace: namespace, recovered: make(map[string]TruncationReport)}
}

// Recover runs entityID's torn-tail scan if it has not already run on this
// SQLiteStore instance, and returns its report. Append and Replay call this
// internally; a caller may also call it directly to observe the report.
func (s *SQLiteStore) Recover(ctx context.Context, entityID string) (TruncationReport, error) {
	lock := s.lockFor(entityID)
	lock.Lock()
	defer lock.Unlock()
	return s.recoverEntityLocked(ctx, entityID)
}

// Close releases no resources of its own: the underlying provider.Store
// was constructed by, and remains owned by, New's caller, so closing it
// here would risk a double-close against a store other packages may still
// be using.
func (s *SQLiteStore) Close() error { return nil }

// lockFor returns the per-entity mutex Append serializes through. The
// SQLite write-executor already allows only one Tx in flight for the whole
// process, but that alone does not stop two concurrent goroutines from
// each reading the same not-yet-advanced head before either commits; this
// lock is what makes "seq is allocated monotonically per entity" true for
// concurrent callers within one process rather than merely within one
// transaction. Different entities never contend for the same lock.
func (s *SQLiteStore) lockFor(entityID string) *sync.Mutex {
	v, _ := s.entityLocks.LoadOrStore(entityID, &sync.Mutex{})
	return v.(*sync.Mutex)
}

// Append seals a new entry as entityID's next sequence number and commits
// it durably before returning. Ordering is by the log's own per-entity
// sequence number, not by timestamp, so two entries appended within one
// clock tick still have exactly one defined order.
func (s *SQLiteStore) Append(ctx context.Context, entityID string, kind Kind, operationID string, payload json.RawMessage) (Entry, error) {
	if err := validateAppendInput(entityID, kind, operationID, payload); err != nil {
		return Entry{}, err
	}
	lock := s.lockFor(entityID)
	lock.Lock()
	defer lock.Unlock()
	if _, err := s.recoverEntityLocked(ctx, entityID); err != nil {
		return Entry{}, err
	}
	var result Entry
	txErr := s.store.Tx(ctx, func(ctx context.Context, tx provider.Tx) error {
		e, err := s.commitEntryTx(ctx, tx, entityID, kind, operationID, payload)
		if err != nil {
			return err
		}
		result = e
		return nil
	})
	if txErr != nil {
		return Entry{}, wrapStore(txErr, "journal: appending entry")
	}
	return result, nil
}

// commitEntryTx allocates the next sequence number for entityID from
// inside tx (so two callers can never mint the same one — the SQLite
// driver serializes every Tx through its single write connection) and
// writes the sealed entry and the advanced head pointer together, so
// neither can land without the other.
func (s *SQLiteStore) commitEntryTx(ctx context.Context, tx provider.Tx, entityID string, kind Kind, operationID string, payload json.RawMessage) (Entry, error) {
	head, err := s.loadHeadFrom(ctx, tx, entityID)
	if err != nil {
		return Entry{}, err
	}
	seq := head + 1
	e, err := seal(Entry{
		EntityID:    entityID,
		Seq:         seq,
		Kind:        kind,
		OperationID: operationID,
		Payload:     payload,
		TSUnixNano:  s.clock.Now().UTC().UnixNano(),
	})
	if err != nil {
		return Entry{}, err
	}
	data, err := json.Marshal(e)
	if err != nil {
		return Entry{}, cascade.Wrap(cascade.KindInternal, err, "journal: encoding entry")
	}
	if err := tx.CompareAndSwap(ctx, s.namespace, entryKey(entityID, seq), nil, data); err != nil {
		return Entry{}, cascade.Wrapf(cascade.KindConflict, ErrAlreadyRecorded, "entity %s seq %d: %v", entityID, seq, err)
	}
	headData, err := json.Marshal(headRecord{Seq: seq})
	if err != nil {
		return Entry{}, cascade.Wrap(cascade.KindInternal, err, "journal: encoding head")
	}
	if err := tx.Put(ctx, s.namespace, headKey(entityID), headData); err != nil {
		return Entry{}, err
	}
	return e, nil
}

// loadHeadFrom reads entityID's head pointer through g (either the top-
// level store or an in-flight transaction). A never-appended entity reads
// as head 0 with a nil error.
func (s *SQLiteStore) loadHeadFrom(ctx context.Context, g getter, entityID string) (uint64, error) {
	data, err := g.Get(ctx, s.namespace, headKey(entityID))
	if err != nil {
		if cascade.HasKind(err, cascade.KindNotFound) {
			return 0, nil
		}
		return 0, wrapStore(err, "journal: reading head")
	}
	var h headRecord
	if uerr := json.Unmarshal(data, &h); uerr != nil {
		return 0, cascade.Wrapf(cascade.KindIntegrity, ErrTampered, "head record for entity %s is not decodable: %v", entityID, uerr)
	}
	return h.Seq, nil
}
