//! `cascade completions <shell>` — print shell completion script to stdout.
//!
//! # Purpose
//!
//! Print a ready-to-use shell completion script for the `cascade` binary.
//! Completion scripts are embedded in the binary at compile time via
//! `include_str!` so the command works offline and without any runtime
//! dependency on `clap_complete`.
//!
//! # Inputs
//!
//! - `shell`: one of `bash`, `zsh`, `fish`, `powershell` (case-insensitive).
//!
//! # Outputs
//!
//! Writes the completion script to stdout.  Exits 1 with a message to stderr
//! when an unsupported shell is requested.
//!
//! # Constraints
//!
//! Completions are generated by `build.rs` using `clap_complete::generate_to`
//! and embedded via `include_str!`.  When new subcommands are added, both
//! `build.rs` and `cmd/mod.rs` must be updated to keep the completions in
//! sync; a clean `cargo build` regenerates the embedded scripts.
//!
//! # SPORT
//!
//! `.claude/docs/MASTER-CLI.md` — `cascade completions` row

use async_trait::async_trait;
use clap::{Args, ValueEnum};

use cascade_types::error::Result;

use super::Command;

// ---------------------------------------------------------------------------
// Embedded completion scripts (generated by build.rs via clap_complete)
// ---------------------------------------------------------------------------

/// Bash completion script embedded at compile time.
const BASH: &str = include_str!(concat!(env!("OUT_DIR"), "/completions/cascade.bash"));

/// Zsh completion script embedded at compile time.
const ZSH: &str = include_str!(concat!(env!("OUT_DIR"), "/completions/_cascade"));

/// Fish completion script embedded at compile time.
const FISH: &str = include_str!(concat!(env!("OUT_DIR"), "/completions/cascade.fish"));

/// PowerShell completion script embedded at compile time.
const POWERSHELL: &str = include_str!(concat!(env!("OUT_DIR"), "/completions/_cascade.ps1"));

// ---------------------------------------------------------------------------
// Argument types
// ---------------------------------------------------------------------------

/// Supported shells for completion generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub enum ShellArg {
    /// Bash (≥4.1): source with `source <(cascade completions bash)`.
    Bash,
    /// Zsh: place in `$fpath`, e.g. `~/.zsh/completions/_cascade`.
    Zsh,
    /// Fish: place in `~/.config/fish/completions/cascade.fish`.
    Fish,
    /// PowerShell: pipe through `Invoke-Expression` or dot-source a file.
    Powershell,
}

/// Arguments for `cascade completions`.
#[derive(Debug, Args)]
pub struct CompletionsArgs {
    /// Target shell.
    pub shell: ShellArg,
}

// ---------------------------------------------------------------------------
// Command implementation
// ---------------------------------------------------------------------------

#[async_trait]
impl Command for CompletionsArgs {
    /// Print the embedded completion script for the requested shell.
    async fn run(&self) -> Result<()> {
        let script = match self.shell {
            ShellArg::Bash => BASH,
            ShellArg::Zsh => ZSH,
            ShellArg::Fish => FISH,
            ShellArg::Powershell => POWERSHELL,
        };
        print!("{script}");
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bash_script_is_non_empty() {
        assert!(!BASH.is_empty(), "bash completion script must not be empty");
    }

    #[test]
    fn bash_script_contains_binary_name() {
        assert!(
            BASH.contains("cascade"),
            "bash completion script must reference 'cascade'"
        );
    }

    #[test]
    fn zsh_script_is_non_empty() {
        assert!(!ZSH.is_empty(), "zsh completion script must not be empty");
    }

    #[test]
    fn zsh_script_has_compdef_header() {
        assert!(
            ZSH.contains("#compdef cascade") || ZSH.contains("_cascade"),
            "zsh completion script must have a compdef header or _cascade function"
        );
    }

    #[test]
    fn fish_script_is_non_empty() {
        assert!(!FISH.is_empty(), "fish completion script must not be empty");
    }

    #[test]
    fn powershell_script_is_non_empty() {
        assert!(
            !POWERSHELL.is_empty(),
            "powershell completion script must not be empty"
        );
    }

    #[tokio::test]
    async fn completions_run_bash_returns_ok() {
        let args = CompletionsArgs {
            shell: ShellArg::Bash,
        };
        assert!(args.run().await.is_ok());
    }

    #[tokio::test]
    async fn completions_run_zsh_returns_ok() {
        let args = CompletionsArgs {
            shell: ShellArg::Zsh,
        };
        assert!(args.run().await.is_ok());
    }

    #[tokio::test]
    async fn completions_run_fish_returns_ok() {
        let args = CompletionsArgs {
            shell: ShellArg::Fish,
        };
        assert!(args.run().await.is_ok());
    }

    #[tokio::test]
    async fn completions_run_powershell_returns_ok() {
        let args = CompletionsArgs {
            shell: ShellArg::Powershell,
        };
        assert!(args.run().await.is_ok());
    }

    #[test]
    fn shell_arg_all_variants_covered() {
        // Ensure all 4 shells can be matched without panic.
        let shells = [
            ShellArg::Bash,
            ShellArg::Zsh,
            ShellArg::Fish,
            ShellArg::Powershell,
        ];
        for shell in shells {
            let script = match shell {
                ShellArg::Bash => BASH,
                ShellArg::Zsh => ZSH,
                ShellArg::Fish => FISH,
                ShellArg::Powershell => POWERSHELL,
            };
            assert!(!script.is_empty());
        }
    }

    #[test]
    fn completions_args_shell_parses_via_value_enum() {
        use clap::Parser;

        #[derive(Parser)]
        struct TestCli {
            #[command(subcommand)]
            cmd: crate::cmd::Commands,
        }

        let args = vec!["cascade", "completions", "bash"];
        let cli = TestCli::try_parse_from(args).unwrap();
        match cli.cmd {
            crate::cmd::Commands::Completions(c) => {
                assert_eq!(c.shell, ShellArg::Bash);
            }
            _ => panic!("expected Completions command"),
        }
    }
}
