// Purpose: aggregate a Sweeper+Resolver run's hits into one row per
// (pointer, path) pair, render them as the committed Markdown inventory
// and the machine-readable unresolved set, and orchestrate the full
// scan/resolve/write cycle Run() dispatches into.
// Inputs: the []Hit a sweep run produces (one per (term, path, line)),
// aggregated here into unique (term, path) pairs — line numbers never
// reach a committed output, only the --dry-run path.
// Outputs: docs/migration/v1-pointer-inventory.md (pointer | path |
// disposition | replacement | decommission-safe) and docs/migration/
// unresolved.json (rewritten from scratch every non-dry run as exactly
// that run's UNRESOLVED (pointer, path) pairs).
// Constraints: idempotent — identical input produces byte-identical
// output, so a second run on an unchanged tree never drifts. Never names
// os.Stdout/os.Stderr directly: run()/finish() take the one
// internal/output.Writer sweep.go's Run() constructs.
// SPORT: migration/sweep: term-file resolver rewrite.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/acamarata/cascade/internal/output"
	"github.com/acamarata/cascade/internal/runtime"
)

// Row is one classified (pointer, path) pair, ready to render.
type Row struct {
	Term        Term
	Path        string
	Disposition Disposition
	Replacement []string
	Reason      string // set only for UNRESOLVED
}

// decommissionSafe renders the Writer's fifth column: "yes" only when the
// term is DONE, "no" for every other disposition. A PROVENANCE row is
// "no": an accepted citation (a live v2 marker, a live v2 field, a design
// note) is never itself a retirement candidate. A DONE row whose anchor is
// referenced by non-migration production code must be declared PROVENANCE
// instead (TestResolve_LiveAnchorNeverDecommissionSafe enforces it).
func (row Row) decommissionSafe() string {
	if row.Disposition == DispositionDone {
		return "yes"
	}
	return "no"
}

// pointerHash hashes a row's pointer (its term text) for the stable,
// content-derived sort key — never a timestamp or incidental host path.
func pointerHash(pointer string) string {
	sum := sha256.Sum256([]byte(pointer))
	return hex.EncodeToString(sum[:])
}

// sortRows orders rows by (sha256(pointer), path) so identical input
// always produces identical output regardless of the scan's internal
// iteration order.
func sortRows(rows []Row) {
	sort.Slice(rows, func(i, j int) bool {
		hi, hj := pointerHash(rows[i].Term.Term), pointerHash(rows[j].Term.Term)
		if hi != hj {
			return hi < hj
		}
		return rows[i].Path < rows[j].Path
	})
}

// renderTable renders rows as the committed Markdown table body (header
// included). One row per (pointer, path) — no line numbers, no counts.
func renderTable(rows []Row) string {
	var b strings.Builder
	b.WriteString("| pointer | path | disposition | replacement | decommission-safe |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for _, row := range rows {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n",
			row.Term.Term, row.Path, row.Disposition, strings.Join(row.Replacement, ", "), row.decommissionSafe())
	}
	return b.String()
}

// WriteMarkdown writes the sorted table to path via runtime.WriteBytesAtomic
// (internal/runtime/toml_atomic_write.go) — never a bare stdlib file write
// or an own temp-plus-rename. When the runtime package gains a
// permission-taking atomic-file helper, this call switches to it.
func WriteMarkdown(rows []Row, path string) error {
	sorted := append([]Row(nil), rows...)
	sortRows(sorted)
	body := "# v1 pointer inventory\n\nGenerated by `go run ./internal/migration/sweep --files <(git ls-files -z)`. Do not hand-edit.\n\n" +
		renderTable(sorted)
	if err := runtime.WriteBytesAtomic(path, []byte(body)); err != nil {
		return fmt.Errorf("sweep: writing %s: %w", path, err)
	}
	return nil
}

// unresolvedEntry is one docs/migration/unresolved.json array element.
type unresolvedEntry struct {
	Pointer string `json:"pointer"`
	Class   string `json:"class"`
	Path    string `json:"path"`
	Reason  string `json:"reason"`
}

// WriteUnresolvedJSON rewrites path from scratch as exactly rows' UNRESOLVED
// entries, sorted by pointer hash: a pointer that has since resolved
// disappears, and no resolved pointer lingers. An UNRESOLVED row with an
// empty or blank reason is refused before anything is written: every
// committed entry must say why it is unresolved.
func WriteUnresolvedJSON(rows []Row, path string) error {
	sorted := append([]Row(nil), rows...)
	sortRows(sorted)
	entries := []unresolvedEntry{}
	for _, row := range sorted {
		if row.Disposition != DispositionUnresolved {
			continue
		}
		if strings.TrimSpace(row.Reason) == "" {
			return fmt.Errorf("sweep: UNRESOLVED row (%s, %s) has an empty reason; refusing to write %s",
				row.Term.Term, row.Path, path)
		}
		entries = append(entries, unresolvedEntry{
			Pointer: row.Term.Term, Class: row.Term.Class, Path: row.Path, Reason: row.Reason,
		})
	}
	data, err := json.MarshalIndent(entries, "", "  ")
	if err != nil {
		return fmt.Errorf("sweep: rendering %s: %w", path, err)
	}
	if err := runtime.WriteBytesAtomic(path, append(data, '\n')); err != nil {
		return fmt.Errorf("sweep: writing %s: %w", path, err)
	}
	return nil
}

// rowKey identifies one (term, path) aggregation bucket.
type rowKey struct{ term, path string }

// buildRows aggregates hits into one Row per unique (term, path) pair —
// a term hit on ten different lines of the same file is exactly one row,
// per the committed inventory's path-level (never line-level) contract. A
// (path, term) in provSet is PROVENANCE; otherwise every hit of a given
// term shares that term's single Resolver.Resolve outcome (cached so a
// term declared "done" with a missing replacement is reported once, not
// once per occurrence).
func buildRows(hits []Hit, provSet map[string]bool, resolver *Resolver) ([]Row, error) {
	seen := make(map[rowKey]bool, len(hits))
	cache := map[string]Disposition{}
	var rows []Row
	for _, h := range hits {
		k := rowKey{h.Term.Term, h.Path}
		if seen[k] {
			continue
		}
		seen[k] = true
		if provSet[h.Path+"|"+h.Term.Term] {
			rows = append(rows, Row{Term: h.Term, Path: h.Path, Disposition: DispositionProvenance})
			continue
		}
		disp, ok := cache[h.Term.Term]
		if !ok {
			var err error
			disp, err = resolver.Resolve(h.Term)
			if err != nil {
				return nil, err
			}
			cache[h.Term.Term] = disp
		}
		row := Row{Term: h.Term, Path: h.Path, Disposition: disp, Replacement: h.Term.Replacement}
		if disp == DispositionUnresolved {
			row.Reason = "no declared v2 replacement"
		}
		rows = append(rows, row)
	}
	return rows, nil
}

// staleProvenanceRefs returns every provRefs entry whose (path, term) has
// no matching hit: a provenance citation naming a pointer the tree no
// longer contains is stale input, not a silent no-op.
func staleProvenanceRefs(provRefs []ProvenanceRef, hits []Hit) []ProvenanceRef {
	hitSet := make(map[string]bool, len(hits))
	for _, h := range hits {
		hitSet[h.Path+"|"+h.Term.Term] = true
	}
	var stale []ProvenanceRef
	for _, r := range provRefs {
		if !hitSet[r.Path+"|"+r.Term] {
			stale = append(stale, r)
		}
	}
	return stale
}

// run executes the full scan/resolve/write cycle for Run(). files is
// already filterTracked()'d. w is the one internal/output.Writer Run()
// constructed; every diagnostic this function (and finish()) emits goes
// through it, never a bare os.Stderr/os.Stdout reference.
func run(root string, terms []Term, provRefs []ProvenanceRef, files []string, dryRun, failOnUnresolved bool, w *output.Writer) int {
	hits, err := (Sweeper{Root: root, Terms: terms, Files: files}).Scan()
	if err != nil {
		w.Fail(err)
		return 2
	}
	if stale := staleProvenanceRefs(provRefs, hits); len(stale) > 0 {
		w.Fail(fmt.Errorf("sweep: %d stale provenance-refs entr(y/ies) with no matching hit: %v", len(stale), stale))
		return 2
	}
	provSet := make(map[string]bool, len(provRefs))
	for _, r := range provRefs {
		provSet[r.Path+"|"+r.Term] = true
	}
	resolver := &Resolver{Root: root}
	rows, err := buildRows(hits, provSet, resolver)
	if err != nil {
		w.Fail(err)
		return 2
	}
	return finish(rows, hits, terms, root, dryRun, failOnUnresolved, w)
}

// finish prints or writes rows and computes the final exit code.
func finish(rows []Row, hits []Hit, terms []Term, root string, dryRun, failOnUnresolved bool, w *output.Writer) int {
	if dryRun {
		w.Println(dryRunText(hits, terms))
	} else {
		if err := WriteMarkdown(rows, filepath.Join(root, "docs", "migration", "v1-pointer-inventory.md")); err != nil {
			w.Fail(err)
			return 2
		}
		if err := WriteUnresolvedJSON(rows, filepath.Join(root, "docs", "migration", "unresolved.json")); err != nil {
			w.Fail(err)
			return 2
		}
	}
	unresolved := 0
	for _, row := range rows {
		if row.Disposition == DispositionUnresolved {
			unresolved++
		}
	}
	if failOnUnresolved && unresolved > 0 {
		return 3
	}
	return 0
}

// dryRunText renders --dry-run's stdout: every hit's exact path:line
// location, followed by a per-declared-term hit-count table (zero counts
// included for a term the tree never mentions) — never written to the
// committed outputs.
func dryRunText(hits []Hit, terms []Term) string {
	var b strings.Builder
	sorted := append([]Hit(nil), hits...)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].Path != sorted[j].Path {
			return sorted[i].Path < sorted[j].Path
		}
		if sorted[i].Line != sorted[j].Line {
			return sorted[i].Line < sorted[j].Line
		}
		return sorted[i].Term.Term < sorted[j].Term.Term
	})
	b.WriteString("| pointer | location |\n|---|---|\n")
	for _, h := range sorted {
		fmt.Fprintf(&b, "| %s | %s:%d |\n", h.Term.Term, h.Path, h.Line)
	}
	counts := map[string]int{}
	for _, h := range hits {
		counts[h.Term.Term]++
	}
	sortedTerms := append([]Term(nil), terms...)
	sort.Slice(sortedTerms, func(i, j int) bool { return sortedTerms[i].Term < sortedTerms[j].Term })
	b.WriteString("\n| term | hits |\n|---|---|\n")
	for _, t := range sortedTerms {
		fmt.Fprintf(&b, "| %s | %d |\n", t.Term, counts[t.Term])
	}
	return strings.TrimRight(b.String(), "\n")
}
