// Purpose: render each migration/ dir's README: what the fixtures are, the
// domain's redaction policy, how to regenerate and extend them, and the
// provenance table.
// Inputs: the provenance rows already on disk and the rows of this run.
// Outputs: deterministic README bytes; a row is keyed by (domain, input
// digest, format version), never duplicated, and keeps its first capture
// date.
// Constraints: the README holds no machine path, no secret and no value
// from an input; it is guarded like a fixture before it is written.
// SPORT: migration/golden/ADD (P1-E26-W10-S54-T3).
package main

import (
	"sort"
	"strings"

	v1 "github.com/acamarata/cascade/internal/migration/v1"
	"github.com/acamarata/cascade/internal/secrets"
	"github.com/acamarata/cascade/pkg/cascade"
)

// redactionPolicy is each domain's README policy paragraph.
var redactionPolicy = map[v1.Domain]string{
	v1.DomainMemory: "Each record holds the v2 file the memory FileStore wrote, read back. Frontmatter keys the " +
		"importer and the FileStore batch set (format, name, kind, description, scope_ref, confidence, origin, " +
		"session_id, created_at, updated_at, content_hash) and the body are kept; every other key is present with " +
		"the value REDACTED. The importer's Change keeps operation, target and the body hash; source is the " +
		"input-relative path.",
	v1.DomainVault: "Before import, every entry name is renamed to a synthetic MIG_FIXTURE_SECRET name with a 1-based " +
		"index and every value to a " +
		"synthetic non-secret, in a scratch home whose custody is forced to the encrypted file vault under the " +
		"dedicated harvest service label. Each record keeps only the importer's Changes: operation is kept, " +
		"target becomes NAME-<n>, source is the input-relative path and content_hash is REDACTED.",
	v1.DomainAccounts: "Each record holds every provider record read back from a scratch registry. Driver, Auth, " +
		"AccountKind, Tier and KnownModels are kept; Name becomes ACCOUNT-<n>, AuthRef becomes NAME-<n>, and every " +
		"other field is REDACTED. Changes, journal entries and re-auth prompts pass only through the same " +
		"NAME-/ACCOUNT- maps; anything they do not map is REDACTED.",
	v1.DomainConfig: "Each input is imported in its own scratch home. A record keeps the v2 keys the v1 config " +
		"translator maps (schema_version, logging.level, logging.format, daemon.socket, telemetry.enabled); an " +
		"absolute path value becomes REDACTED-PATH and every other key's value is REDACTED, never dropped. A " +
		"translator refusal (unknown v1 keys) is committed as config-refusal-<hash>.json with the refused key " +
		"paths instead of being skipped.",
}

// parseRows reads the provenance table rows from README text.
func parseRows(text string) []provenanceRow {
	var out []provenanceRow
	for _, line := range strings.Split(text, "\n") {
		if !strings.HasPrefix(line, "| ") || !strings.HasSuffix(line, " |") {
			continue
		}
		cells := strings.Split(strings.TrimSuffix(strings.TrimPrefix(line, "| "), " |"), " | ")
		if len(cells) != 5 || !isSHA256Hex(cells[2]) {
			continue
		}
		out = append(out, provenanceRow{Domain: cells[0], Input: cells[1], Digest: cells[2], Format: cells[3], Captured: cells[4]})
	}
	return out
}

// mergeRows adds each new row whose key is absent, stamped with captured,
// and returns every row sorted. A duplicated key already on disk refuses.
func mergeRows(existing, incoming []provenanceRow, captured string) ([]provenanceRow, error) {
	byKey := make(map[string]provenanceRow, len(existing)+len(incoming))
	for _, row := range existing {
		if _, dup := byKey[row.key()]; dup {
			return nil, cascade.New(cascade.KindIntegrity, "golden harvest: a README repeats a provenance row")
		}
		byKey[row.key()] = row
	}
	for _, row := range incoming {
		if _, ok := byKey[row.key()]; !ok {
			row.Captured = captured
			byKey[row.key()] = row
		}
	}
	out := make([]provenanceRow, 0, len(byKey))
	for _, row := range byKey {
		out = append(out, row)
	}
	sort.Slice(out, func(i, j int) bool {
		a, b := out[i], out[j]
		return a.Domain+"\x00"+a.Input+"\x00"+a.Digest+"\x00"+a.Format < b.Domain+"\x00"+b.Input+"\x00"+b.Digest+"\x00"+b.Format
	})
	return out, nil
}

// renderReadme renders the whole README for domain.
func renderReadme(domain v1.Domain, rows []provenanceRow) []byte {
	var b strings.Builder
	d := string(domain)
	b.WriteString("# v1 importer golden fixtures: " + d + "\n\n")
	b.WriteString("GENERATED BY `go run ./internal/migration/golden`. DO NOT HAND EDIT.\n\n")
	b.WriteString("Each `" + d + "-<16 hex>.json` file is one record the real v1 " + d + " importer produced from one " +
		"digest-pinned input under `" + pinnedInputDir + "/`, passed through the harvester's allowlist Redactor. " +
		"The name is the first 16 hex digits of the sha256 of the file's canonical JSON (sorted keys, 2-space " +
		"indent, LF, one trailing newline).\n\n")
	b.WriteString("## Redaction policy\n\n" + redactionPolicy[domain] + "\n\n")
	b.WriteString("## Regenerate\n\n    go run ./internal/migration/golden [--domain " + d + "] [--dry-run]\n\n")
	b.WriteString("A repeat run over unchanged inputs writes nothing. To extend the input set, add the file under " +
		"the pinned input dir, add its line to `INPUTS.sha256` (`<sha256>  <path>`, sorted by path), and run the " +
		"harvester; it refuses any file the manifest does not list or whose digest differs.\n\n")
	b.WriteString("## Provenance\n\n| domain | input | input sha256 | format | captured |\n|---|---|---|---|---|\n")
	for _, row := range rows {
		b.WriteString("| " + row.Domain + " | " + row.Input + " | " + row.Digest + " | " + row.Format + " | " + row.Captured + " |\n")
	}
	return []byte(b.String())
}

// guardReadme applies the fixture output guard to rendered README bytes.
func guardReadme(data []byte) error {
	det, err := secrets.NewDetector(secrets.DefaultRegistry(), secrets.DefaultDetectionConfig())
	if err != nil {
		return cascade.Wrap(cascade.KindInternal, err, "golden harvest: build the secret detector")
	}
	return guardBytes(det, readmeName, data)
}
