//! Shared request/response types for the cascade-providers crate.
//!
//! # Purpose
//!
//! Defines the wire-format-agnostic types that every `ProviderAdapter`
//! implementation sends and receives.  These types are deliberately minimal
//! — they cover the intersection of the Anthropic Messages API and the
//! OpenAI Chat Completions API so adapters can translate without loss.
//!
//! # Inputs / Outputs
//!
//! All types implement `Serialize + Deserialize` with `serde`.  Enum
//! discriminants use `snake_case` to match both API conventions.  Struct
//! fields use `snake_case` (Rust default — no rename needed on structs).
//!
//! # Constraints
//!
//! - `MessageRole` serializes to `"system"`, `"user"`, or `"assistant"` for
//!   compatibility with both Anthropic and OpenAI.
//! - `StreamChunk::finish_reason` is `Option<String>` because providers use
//!   different strings (`"stop"`, `"end_turn"`, `"length"`, etc.).
//! - `TokenUsage` fields are `u32`; no provider returns negative token counts.

use serde::{Deserialize, Serialize};

// ── MessageRole ───────────────────────────────────────────────────────────────

/// The role of a participant in a conversation turn.
///
/// Serializes to lowercase strings to match both Anthropic and OpenAI
/// message formats.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum MessageRole {
    /// A system-level instruction that sets context for the assistant.
    System,
    /// A message from the end user.
    User,
    /// A message generated by the AI assistant.
    Assistant,
}

// ── Message ───────────────────────────────────────────────────────────────────

/// A single turn in a conversation.
///
/// Maps directly to the `messages` array element in both Anthropic and OpenAI
/// chat APIs.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Message {
    /// The role of the author.
    pub role: MessageRole,
    /// The text content of this turn.
    pub content: String,
}

impl Message {
    /// Convenience constructor — `Message::user("hello")`.
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role: MessageRole::User,
            content: content.into(),
        }
    }

    /// Convenience constructor — `Message::assistant("hi there")`.
    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            role: MessageRole::Assistant,
            content: content.into(),
        }
    }

    /// Convenience constructor — `Message::system("You are …")`.
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            role: MessageRole::System,
            content: content.into(),
        }
    }
}

// ── TokenUsage ────────────────────────────────────────────────────────────────

/// Token counts returned by the provider after a completion call.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct TokenUsage {
    /// Tokens in the input prompt (system + messages).
    pub prompt_tokens: u32,
    /// Tokens generated in the completion.
    pub completion_tokens: u32,
    /// Total tokens consumed (`prompt_tokens + completion_tokens`).
    pub total_tokens: u32,
}

// ── CompletionRequest ─────────────────────────────────────────────────────────

/// A request to generate a completion from a provider.
///
/// Adapters translate this into their provider-specific wire format.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CompletionRequest {
    /// The model identifier (e.g. `"claude-3-5-sonnet-20241022"`,
    /// `"gpt-4o"`, `"gemini-1.5-pro"`).
    pub model: String,

    /// Conversation history.  The final message is normally a `User` turn.
    pub messages: Vec<Message>,

    /// Maximum tokens the model may generate.  `None` uses the provider
    /// default.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u32>,

    /// Sampling temperature in `[0.0, 2.0]`.  `None` uses the provider
    /// default.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f32>,

    /// Whether to stream the response token-by-token.
    pub stream: bool,

    /// Optional system prompt (passed separately from `messages` for
    /// providers that have a dedicated system-prompt field).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system: Option<String>,
}

impl CompletionRequest {
    /// Build a minimal non-streaming request.
    pub fn simple(model: impl Into<String>, user_message: impl Into<String>) -> Self {
        Self {
            model: model.into(),
            messages: vec![Message::user(user_message)],
            max_tokens: None,
            temperature: None,
            stream: false,
            system: None,
        }
    }
}

// ── CompletionResponse ────────────────────────────────────────────────────────

/// A completed (non-streaming) response from a provider.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CompletionResponse {
    /// The generated text.
    pub content: String,

    /// The model that produced this response (may differ from the requested
    /// model if the provider re-routes).
    pub model: String,

    /// Token consumption for this call.
    pub usage: TokenUsage,

    /// Estimated USD cost for this call, computed from the static pricing
    /// table in [`crate::cost`] (snapshot 2026-05-31 — approximate).
    ///
    /// - `Some(usd)` when the model is in the pricing table (including local
    ///   models, which return `Some(0.0)`).
    /// - `None` when the model is not in the table.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cost_usd: Option<f64>,
}

// ── StreamChunk ───────────────────────────────────────────────────────────────

/// A single event from a streaming completion response.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StreamChunk {
    /// The incremental text fragment for this chunk.
    pub delta: String,

    /// Why the stream ended.  `None` while generation is ongoing; `Some(_)`
    /// on the final chunk (e.g. `"stop"`, `"end_turn"`, `"length"`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub finish_reason: Option<String>,
}

// ── ModelInfo ─────────────────────────────────────────────────────────────────

/// Metadata about a single model available on a provider.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ModelInfo {
    /// Provider-specific model identifier (e.g. `"claude-3-5-sonnet-20241022"`).
    pub id: String,

    /// Human-readable display name (e.g. `"Claude 3.5 Sonnet"`).
    pub name: String,

    /// Maximum tokens the model can process in a single request (prompt +
    /// completion combined).
    pub context_window: u32,

    /// Whether this model supports streaming via `complete_stream`.
    pub supports_streaming: bool,
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // Helper: round-trip a value through JSON and assert equality.
    fn round_trip<T: Serialize + for<'de> Deserialize<'de> + PartialEq + std::fmt::Debug>(
        value: &T,
    ) {
        let json = serde_json::to_string(value).expect("serialize");
        let back: T = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(value, &back);
    }

    #[test]
    fn message_role_serializes_lowercase() {
        let json = serde_json::to_string(&MessageRole::System).unwrap();
        assert_eq!(json, r#""system""#);
        let json = serde_json::to_string(&MessageRole::User).unwrap();
        assert_eq!(json, r#""user""#);
        let json = serde_json::to_string(&MessageRole::Assistant).unwrap();
        assert_eq!(json, r#""assistant""#);
    }

    #[test]
    fn message_role_round_trip() {
        round_trip(&MessageRole::System);
        round_trip(&MessageRole::User);
        round_trip(&MessageRole::Assistant);
    }

    #[test]
    fn message_round_trip() {
        let msg = Message::user("Hello, world!");
        round_trip(&msg);
    }

    #[test]
    fn token_usage_round_trip() {
        let usage = TokenUsage {
            prompt_tokens: 100,
            completion_tokens: 50,
            total_tokens: 150,
        };
        round_trip(&usage);
    }

    #[test]
    fn completion_request_round_trip() {
        let req = CompletionRequest {
            model: "claude-3-5-sonnet-20241022".into(),
            messages: vec![
                Message::system("You are a helpful assistant."),
                Message::user("What is 2 + 2?"),
            ],
            max_tokens: Some(256),
            temperature: Some(0.7),
            stream: false,
            system: None,
        };
        round_trip(&req);
    }

    #[test]
    fn completion_response_round_trip() {
        let resp = CompletionResponse {
            content: "The answer is 4.".into(),
            model: "claude-3-5-sonnet-20241022".into(),
            usage: TokenUsage {
                prompt_tokens: 20,
                completion_tokens: 8,
                total_tokens: 28,
            },
            cost_usd: Some(0.00018),
        };
        round_trip(&resp);
    }

    #[test]
    fn completion_response_cost_usd_omitted_when_none() {
        let resp = CompletionResponse {
            content: "hello".into(),
            model: "unknown-model".into(),
            usage: TokenUsage::default(),
            cost_usd: None,
        };
        let json = serde_json::to_string(&resp).unwrap();
        assert!(!json.contains("cost_usd"), "None should be omitted: {json}");
    }

    #[test]
    fn completion_response_cost_usd_present_when_some() {
        let resp = CompletionResponse {
            content: "hi".into(),
            model: "gpt-4o".into(),
            usage: TokenUsage {
                prompt_tokens: 100,
                completion_tokens: 50,
                total_tokens: 150,
            },
            cost_usd: Some(0.00075),
        };
        let json = serde_json::to_string(&resp).unwrap();
        assert!(
            json.contains("cost_usd"),
            "Some should be serialized: {json}"
        );
        let back: CompletionResponse = serde_json::from_str(&json).unwrap();
        assert_eq!(back.cost_usd, Some(0.00075));
    }

    #[test]
    fn stream_chunk_round_trip() {
        let chunk = StreamChunk {
            delta: "Hello".into(),
            finish_reason: None,
        };
        round_trip(&chunk);

        let final_chunk = StreamChunk {
            delta: String::new(),
            finish_reason: Some("stop".into()),
        };
        round_trip(&final_chunk);
    }

    #[test]
    fn model_info_round_trip() {
        let info = ModelInfo {
            id: "gpt-4o".into(),
            name: "GPT-4o".into(),
            context_window: 128_000,
            supports_streaming: true,
        };
        round_trip(&info);
    }

    #[test]
    fn completion_request_simple_ctor() {
        let req = CompletionRequest::simple("gpt-4o", "Say hi");
        assert_eq!(req.model, "gpt-4o");
        assert!(!req.stream);
        assert_eq!(req.messages.len(), 1);
        assert_eq!(req.messages[0].role, MessageRole::User);
    }

    #[test]
    fn optional_fields_omitted_in_json() {
        let req = CompletionRequest::simple("m", "q");
        let json = serde_json::to_string(&req).unwrap();
        assert!(!json.contains("max_tokens"), "should be skipped: {json}");
        assert!(!json.contains("temperature"), "should be skipped: {json}");
        assert!(!json.contains("system"), "should be skipped: {json}");
    }
}
