// Purpose: embed the tracked counts.json artifact into the binary, so an
//
//	installed cascade with no source tree on disk can still answer the
//	tree-derived quarter of Report (Providers, Plugins, SPORTLines,
//	Platforms) from the same bytes a website fetching counts.json off
//	GitHub would read.
//
// Inputs: counts.json, generated by internal/inventory/gen and tracked in
//
//	git (never hand-edited — see that generator's doc comment).
//
// Outputs: LoadGenerated, the parsed GeneratedCounts snapshot.
// Constraints: this file must not import anything that would make the
//
//	production binary depend on a live source tree; only encoding/json and
//	the embed itself.
//
// SPORT: internal.inventory.LoadGenerated/ADDED.

package inventory

import (
	_ "embed"
	"encoding/json"
	"fmt"
)

//go:embed counts.json
var generatedCountsJSON []byte

// GeneratedCounts is counts.json's exact shape. Kept distinct from Report
// (rather than embedding Report directly) because Report also carries the
// three live fields (ErrorKinds, StorageDomains, CLICommands) that must
// NEVER be read from this stale, generation-time snapshot — merge.go is
// the only place the two halves are combined.
type GeneratedCounts struct {
	GeneratedAt string   `json:"generated_at"`
	Providers   int      `json:"providers"`
	Plugins     int      `json:"plugins"`
	SPORTLines  int      `json:"sport_lines"`
	Platforms   []string `json:"platforms"`
}

// LoadGenerated parses the embedded counts.json artifact.
func LoadGenerated() (GeneratedCounts, error) {
	var g GeneratedCounts
	if err := json.Unmarshal(generatedCountsJSON, &g); err != nil {
		return GeneratedCounts{}, fmt.Errorf("inventory: parse embedded counts.json: %w", err)
	}
	return g, nil
}
