#!/usr/bin/env bash
# scripts/record_baselines.sh
#
# Run cascade-rag benchmarks and write bench/baselines.json from Criterion output.
#
# Usage:
#   ./scripts/record_baselines.sh
#
# Requirements:
#   - Rust toolchain (stable)
#   - jq (brew install jq / apt install jq)
#
# The script runs `cargo bench -p cascade-rag`, parses the per-benchmark
# estimates.json files that Criterion writes under target/criterion/, and
# emits bench/baselines.json.  The JSON format is intentionally simple so
# the CI regression script can compare it without heavy dependencies.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CRITERION_DIR="${REPO_ROOT}/target/criterion"

echo "[record_baselines] Building and running benchmarks..."
cd "${REPO_ROOT}"
cargo bench -p cascade-rag 2>&1

echo "[record_baselines] Parsing Criterion output from ${CRITERION_DIR}..."

# Build the JSON from all estimates.json files.
# Each file lives at target/criterion/<group>/<bench>/new/estimates.json.
# We use the "median" estimate and, where available, the "throughput" field.

python3 - <<'PYEOF'
import json
import pathlib
import os
import sys
import datetime

root = pathlib.Path(os.environ.get("REPO_ROOT", "."))
crit = root / "target" / "criterion"
out_path = root / "bench" / "baselines.json"

if not crit.exists():
    print(f"[record_baselines] ERROR: {crit} does not exist — run cargo bench first", file=sys.stderr)
    sys.exit(1)

results = {}
for est_file in sorted(crit.rglob("new/estimates.json")):
    # Path: target/criterion/<group>/<bench>/new/estimates.json
    # Drop the "new" and "estimates.json" segments, join the rest as key.
    parts = est_file.relative_to(crit).parts  # (group, bench, "new", "estimates.json")
    key = "/".join(parts[:-2])  # everything except "new/estimates.json"
    try:
        with open(est_file) as f:
            data = json.load(f)
        entry = {"p50_ns": round(data["median"]["point_estimate"])}
        # Throughput file lives alongside estimates.json
        tput_file = est_file.parent / "benchmark.json"
        if tput_file.exists():
            with open(tput_file) as f:
                bdata = json.load(f)
            tput = bdata.get("throughput")
            if tput and "Elements" in tput:
                ns = data["median"]["point_estimate"]
                elems = tput["Elements"]
                per_sec = round(elems / ns * 1e9)
                entry["throughput_items_per_sec"] = per_sec
        results[key] = entry
    except Exception as e:
        print(f"[record_baselines] WARNING: skipping {est_file}: {e}", file=sys.stderr)

if not results:
    print("[record_baselines] ERROR: no estimates.json files found under target/criterion/", file=sys.stderr)
    sys.exit(1)

meta = {
    "_meta": {
        "recorded_at": datetime.date.today().isoformat(),
        "hardware": "see CI runner or local machine",
        "baseline_label": "p4-e04",
        "note": "Generated by scripts/record_baselines.sh. CI runners (ubuntu-latest x86_64) differ from Apple Silicon developer machines; the 20% regression threshold absorbs cross-hardware variance.",
        "criterion_version": "0.5"
    }
}
meta.update(results)

out_path.parent.mkdir(parents=True, exist_ok=True)
with open(out_path, "w") as f:
    json.dump(meta, f, indent=2)
    f.write("\n")

print(f"[record_baselines] Wrote {len(results)} entries to {out_path}")
PYEOF

echo "[record_baselines] Done. Review bench/baselines.json before committing."
