// Package generate holds the machinery every generated repository file
// shares: the generation manifest, the managed-block markers, the
// never-destroy Writer and the drift check (contract:generation-manifest).
//
// A generator writes instruction and config files into a repository
// without ever destroying a byte a human wrote. A file is rewritten only
// when it is byte-identical to the base the last generation left. Any
// other state gets a <file>.cascade-new sidecar and one call to the
// AttentionSink, and the target stays exactly as it was.
//
// The inputs are a repository root, the previous manifest and Rendered
// files (whole-file bytes with every generated byte inside a managed
// block). The outputs are written, adopted or refused files, the next
// manifest and, for Check, a report of exactly four red conditions.
//
// The package imports only the standard library, pkg/cascade and
// internal/runtime. Every write is runtime.WriteFileAtomic or
// runtime.CreateFileAtomic. Every path is resolved under the repository
// root and refused when it crosses a symlink. No managed block carries a
// timestamp, so equal input renders equal bytes.
//
// SPORT: context-engine/generation-manifest (ADD, P1-GEN-05).
package generate
