package generate

// Purpose: the managed-block marker grammar. A managed block is a pair of
//   whole-line markers around generated bytes; everything outside a pair
//   belongs to the human. Three comment forms cover every harness format.
// Inputs: file content and a MarkerForm chosen from the file extension.
// Outputs: the blocks in document order, or an error wrapping
//   ErrMangledMarker that names the offending line.
// Constraints: a marker is never repaired. Leading spaces or tabs on a
//   marker line are allowed (a // marker inside a JSON object is indented);
//   anything else that looks like a marker but is not exactly one
//   (trailing text, missing id, bad id) is mangled, as are an unmatched begin or end, a nested begin, a duplicate
//   id and (when the caller passes a known set) an id outside that set.
//   Text that only mentions a marker inside a longer line is plain text.
// SPORT: context-engine/managed-blocks (ADD, P1-GEN-05).

import (
	"bytes"
	pathpkg "path"
	"regexp"
	"strings"

	"github.com/acamarata/cascade/pkg/cascade"
)

// MarkerForm selects the comment syntax of a managed-block marker.
type MarkerForm int

// The three marker forms.
const (
	// FormMarkdown is <!-- cascade:managed:begin ID --> ... <!-- cascade:managed:end -->.
	FormMarkdown MarkerForm = iota + 1
	// FormHash is # cascade:managed:begin ID ... # cascade:managed:end (TOML).
	FormHash
	// FormSlash is // cascade:managed:begin ID ... // cascade:managed:end.
	FormSlash
)

// ErrMangledMarker is the sentinel every marker error wraps. Compare it
// by identity, never with errors.Is (which compares Kind only).
var ErrMangledMarker = cascade.New(cascade.KindInvalidInput, "generate: mangled managed-block marker")

// blockIDPattern is the closed shape of a block id.
var blockIDPattern = regexp.MustCompile(`^[a-z0-9][a-z0-9@._-]{0,63}$`)

// Block is one managed block: its id and the bytes between its markers.
type Block struct {
	ID   string
	Body []byte
}

// FormFor picks the marker form for a file path by extension: .md uses
// Markdown comments, .toml uses #, and .json, .jsonc and .js use //. Any
// other extension is KindInvalidInput.
func FormFor(path string) (MarkerForm, error) {
	switch strings.ToLower(pathpkg.Ext(path)) {
	case ".md":
		return FormMarkdown, nil
	case ".toml":
		return FormHash, nil
	case ".json", ".jsonc", ".js":
		return FormSlash, nil
	}
	return 0, cascade.Newf(cascade.KindInvalidInput, "generate: no marker form for %q", path)
}

// lead is the comment opener of a marker line, including its space.
func (f MarkerForm) lead() string {
	switch f {
	case FormMarkdown:
		return "<!-- "
	case FormHash:
		return "# "
	case FormSlash:
		return "// "
	}
	return "// "
}

// beginLine renders the begin marker for id, without a line terminator.
func (f MarkerForm) beginLine(id string) string {
	s := f.lead() + "cascade:managed:begin " + id
	if f == FormMarkdown {
		s += " -->"
	}
	return s
}

// endLine renders the end marker, without a line terminator.
func (f MarkerForm) endLine() string {
	s := f.lead() + "cascade:managed:end"
	if f == FormMarkdown {
		s += " -->"
	}
	return s
}

// span locates one block inside content. begin is the first byte of the
// begin line, bodyStart..bodyEnd the bytes between the marker lines, and
// end the byte after the end line including its terminator.
type span struct {
	id                             string
	begin, bodyStart, bodyEnd, end int
}

// scanner is the marker state machine over one file.
type scanner struct {
	form  MarkerForm
	known map[string]bool
	spans []span
	open  *span
	seen  map[string]bool
	line  int
	// openLine is the line of the begin marker still waiting for its end.
	openLine int
}

// mangled builds the error for the current line.
func (s *scanner) mangled(why string) error {
	return cascade.Wrapf(cascade.KindInvalidInput, ErrMangledMarker,
		"generate: mangled managed-block marker: line %d: %s", s.line, why)
}

// begin handles a begin marker whose line starts at start and ends at next.
func (s *scanner) begin(id string, start, next int) error {
	switch {
	case s.open != nil:
		return s.mangled("begin inside open block " + s.open.id)
	case !blockIDPattern.MatchString(id):
		return s.mangled("invalid block id")
	case s.seen[id]:
		return s.mangled("duplicate block id " + id)
	case s.known != nil && !s.known[id]:
		return s.mangled("unknown block id " + id)
	}
	s.seen[id] = true
	s.open = &span{id: id, begin: start, bodyStart: next}
	s.openLine = s.line
	return nil
}

// end handles an end marker whose line starts at start and ends at next.
func (s *scanner) end(start, next int) error {
	if s.open == nil {
		return s.mangled("end without begin")
	}
	s.open.bodyEnd, s.open.end = start, next
	s.spans = append(s.spans, *s.open)
	s.open = nil
	return nil
}

// classify reads one line (terminator stripped). kind is 'b' begin, 'e'
// end, 't' text and 'x' for a marker-shaped line that is not a marker.
func (s *scanner) classify(line string) (kind byte, id string) {
	line = strings.TrimLeft(line, " \t")
	if !strings.HasPrefix(line, s.form.lead()+"cascade:managed:") {
		return 't', ""
	}
	if line == s.form.endLine() {
		return 'e', ""
	}
	head := s.form.lead() + "cascade:managed:begin "
	if !strings.HasPrefix(line, head) {
		return 'x', ""
	}
	id = strings.TrimPrefix(line, head)
	if s.form == FormMarkdown {
		if !strings.HasSuffix(id, " -->") {
			return 'x', ""
		}
		id = strings.TrimSuffix(id, " -->")
	}
	return 'b', id
}

// scanBlocks walks content line by line and returns the block spans. known
// restricts ids when non-nil.
func scanBlocks(content []byte, form MarkerForm, known map[string]bool) ([]span, error) {
	s := &scanner{form: form, known: known, seen: map[string]bool{}}
	for pos := 0; pos < len(content); {
		next := len(content)
		if i := bytes.IndexByte(content[pos:], '\n'); i >= 0 {
			next = pos + i + 1
		}
		s.line++
		line := strings.TrimSuffix(strings.TrimSuffix(string(content[pos:next]), "\n"), "\r")
		kind, id := s.classify(line)
		var err error
		switch kind {
		case 'b':
			err = s.begin(id, pos, next)
		case 'e':
			err = s.end(pos, next)
		case 'x':
			err = s.mangled("malformed marker")
		}
		if err != nil {
			return nil, err
		}
		pos = next
	}
	if s.open != nil {
		s.line = s.openLine
		return nil, s.mangled("begin without end for block " + s.open.id)
	}
	return s.spans, nil
}

// ParseManagedBlocks returns the managed blocks of content in document
// order. known, when non-nil, is the closed set of ids the caller accepts.
func ParseManagedBlocks(content []byte, form MarkerForm, known map[string]bool) ([]Block, error) {
	spans, err := scanBlocks(content, form, known)
	if err != nil {
		return nil, err
	}
	var blocks []Block
	for _, sp := range spans {
		blocks = append(blocks, Block{ID: sp.id, Body: append([]byte(nil), content[sp.bodyStart:sp.bodyEnd]...)})
	}
	return blocks, nil
}

// WrapBlock renders a block: the begin line, body (LF-terminated; an LF is
// added when body is non-empty and lacks one) and the end line.
func WrapBlock(form MarkerForm, id string, body []byte) []byte {
	var b bytes.Buffer
	b.WriteString(form.beginLine(id) + "\n")
	b.Write(lfTerminated(body))
	b.WriteString(form.endLine() + "\n")
	return b.Bytes()
}

// lfTerminated returns body with a final LF when it is non-empty.
func lfTerminated(body []byte) []byte {
	if len(body) == 0 || body[len(body)-1] == '\n' {
		return body
	}
	return append(append([]byte(nil), body...), '\n')
}

// ReplaceManagedBlock swaps the body of block id and leaves every byte
// outside the marker pair unchanged. An absent id is KindNotFound. A body
// that holds a marker-shaped line, or would corrupt the markers, is
// KindInvalidInput wrapping ErrMangledMarker.
func ReplaceManagedBlock(content []byte, form MarkerForm, id string, body []byte) ([]byte, error) {
	spans, err := scanBlocks(content, form, nil)
	if err != nil {
		return nil, err
	}
	for _, sp := range spans {
		if sp.id != id {
			continue
		}
		if err := refuseMarkerBody(form, id, body); err != nil {
			return nil, err
		}
		out := append(append(append([]byte(nil), content[:sp.bodyStart]...), lfTerminated(body)...), content[sp.bodyEnd:]...)
		if err := verifyEdit(id, out, form, spans, ""); err != nil {
			return nil, err
		}
		return out, nil
	}
	return nil, cascade.Newf(cascade.KindNotFound, "generate: no managed block %q", id)
}

// outsideBytes is content with every block's lines (markers included)
// removed: the bytes a human owns.
func outsideBytes(content []byte, spans []span) []byte {
	var out []byte
	pos := 0
	for _, sp := range spans {
		out = append(out, content[pos:sp.begin]...)
		pos = sp.end
	}
	return append(out, content[pos:]...)
}

// isMangled reports whether err is a marker error, by sentinel identity.
func isMangled(err error) bool { return hasSentinel(err, ErrMangledMarker) }
