package generate

// Purpose: the never-destroy Writer. It publishes a rendered file only
//   when the target is absent, already equals the rendering, or is
//   byte-identical to the base the last generation recorded. Every other
//   state is refused: the target stays untouched, <file>.cascade-new holds
//   the rendering, and the AttentionSink hears about it once.
// Inputs: Rendered files and the previous manifest (NewWriter).
// Outputs: one Outcome per file and, from Manifest, the next manifest.
// Constraints: a refusal reason is one of six words (the five Reason
//   constants plus path-escape). With no manifest every existing target is
//   hand-authored. Blocks recorded under another generator are carried
//   into the new content after their hashes verify. A Writer is not safe
//   for concurrent use.
//   Residual window (same-uid race): the target is re-read and compared
//   byte for byte immediately before the write, and the write refuses
//   (outside-edited) when it changed. runtime.WriteFileAtomic then renames
//   a temp file over the path, so an edit landing between that compare and
//   the rename is lost, and a directory swapped for a symlink in that
//   instant can redirect the rename. Closing it needs a rename-if-unchanged
//   primitive the platform does not give us.
// SPORT: context-engine/never-destroy-writer (ADD, P1-GEN-05).

import (
	"bytes"
	"context"
	"time"

	"github.com/acamarata/cascade/internal/runtime"
	"github.com/acamarata/cascade/pkg/cascade"
)

// The refusal reasons. A sixth, ReasonPathEscape, covers confinement.
const (
	ReasonNoManifest    = "no-manifest"
	ReasonUnmanagedFile = "unmanaged-file"
	ReasonMangledMarker = "mangled-marker"
	ReasonBlockEdited   = "managed-block-edited"
	ReasonOutsideEdited = "outside-edited"
	ReasonPathEscape    = "path-escape"
)

// sidecarSuffix names the file a refusal writes beside its target.
const sidecarSuffix = ".cascade-new"

// AttentionSink receives every refusal: the target, its sidecar (empty for
// path-escape) and the reason.
type AttentionSink func(ctx context.Context, target, sidecar, reason string) error

// Rendered is one file a generator wants on disk: the whole file, with
// every generated byte inside a managed block of GeneratorID.
type Rendered struct {
	Path, GeneratorID string
	Content           []byte
}

// Outcome reports what Apply or ApplyBlock did with one file.
type Outcome struct {
	Path             string
	Written, Adopted bool
	Sidecar, Reason  string
}

// Writer applies Rendered files against the last generation's manifest.
type Writer struct {
	root     string
	sink     AttentionSink
	hadPrior bool
	next     map[string]Entry
}

// NewWriter builds a Writer. A nil sink is KindInvalidInput: a refusal
// nobody hears about is a silent loss.
func NewWriter(repoRoot string, sink AttentionSink, prior Manifest, hadPrior bool) (*Writer, error) {
	if sink == nil {
		return nil, cascade.New(cascade.KindInvalidInput, "generate: nil AttentionSink")
	}
	if repoRoot == "" {
		return nil, cascade.New(cascade.KindInvalidInput, "generate: empty repository root")
	}
	w := &Writer{root: repoRoot, sink: sink, hadPrior: hadPrior, next: map[string]Entry{}}
	if hadPrior {
		for _, e := range prior.Entries {
			w.next[e.Path] = e
		}
	}
	return w, nil
}

// Manifest returns the manifest for what this Writer wrote, adopted or
// carried. Refused and untouched files keep their previous entry.
func (w *Writer) Manifest(generatedAt time.Time, deferrals []Deferral) Manifest {
	m := Manifest{Version: ManifestVersion, GeneratedAt: generatedAt.UTC().Format(time.RFC3339), Deferrals: deferrals}
	for _, e := range w.next {
		m.Entries = append(m.Entries, e)
	}
	return canonical(m)
}

// Apply publishes r, or refuses it. A refusal returns a nil error and an
// Outcome with Reason and Sidecar set; an error means the write could not
// be judged or the sink failed after the sidecar was written.
func (w *Writer) Apply(ctx context.Context, r Rendered) (Outcome, error) {
	out := Outcome{Path: r.Path}
	if err := ctx.Err(); err != nil {
		return out, cascade.Wrap(cascade.KindCanceled, err, "generate: apply canceled")
	}
	c, err := openConfined(w.root, r.Path)
	if err != nil {
		return w.escaped(ctx, out, err)
	}
	defer c.close()
	form, err := FormFor(r.Path)
	if err != nil {
		return out, err
	}
	if r.GeneratorID == "" {
		return out, cascade.Newf(cascade.KindInvalidInput, "generate: rendered %s has no generator id", r.Path)
	}
	fresh, err := entryFor(r.Path, r.GeneratorID, r.Content, form, nil)
	if err != nil {
		return out, cascade.Wrapf(cascade.KindInvalidInput, err, "generate: rendered %s is not a valid managed file", r.Path)
	}
	data, exists, err := c.read()
	if err != nil {
		return out, err
	}
	if !exists {
		created, cout, err := w.create(c, r, fresh, out)
		if created || err != nil {
			return cout, err
		}
		if data, exists, err = w.reread(c); isPathEscape(err) {
			return w.escaped(ctx, out, err)
		} else if err != nil || !exists {
			return out, cascade.Wrapf(cascade.KindUnavailable, err, "generate: %s vanished during creation", r.Path)
		}
	}
	return w.evaluate(ctx, c, r, form, data, out)
}

// create publishes r when nothing is at the target. created is false when
// another writer won the race, so the caller judges the file that is there.
func (w *Writer) create(c *confined, r Rendered, fresh Entry, out Outcome) (bool, Outcome, error) {
	if err := c.ensureParent(); err != nil {
		return false, out, err
	}
	beforeCreate(c.rel)
	created, err := runtime.CreateFileAtomic(c.abs, r.Content, 0o644)
	if !created {
		return false, out, err
	}
	w.next[r.Path], out.Written = fresh, true
	return true, out, err
}

// reread re-resolves the target after a lost creation race.
func (w *Writer) reread(c *confined) ([]byte, bool, error) {
	if err := c.walk(); err != nil {
		return nil, false, err
	}
	return c.read()
}

// evaluate judges a file that exists and either adopts, overwrites or
// refuses it. A byte-identical target is adopted only when no entry owns
// it or the entry is this generator's; the recorded block owners stay.
func (w *Writer) evaluate(ctx context.Context, c *confined, r Rendered, form MarkerForm, data []byte, out Outcome) (Outcome, error) {
	if prev, has := w.next[r.Path]; bytes.Equal(data, r.Content) && (!has || prev.GeneratorID == r.GeneratorID) {
		adopted, err := entryFor(r.Path, r.GeneratorID, r.Content, form, owners(prev))
		if err != nil {
			return out, err
		}
		w.next[r.Path], out.Adopted = adopted, true
		return out, nil
	}
	content, reason, err := w.plan(r, form, data)
	if err != nil {
		return out, err
	}
	if reason != "" {
		return w.refuse(ctx, out, r.Path, r.Content, reason)
	}
	return w.overwrite(ctx, c, r, form, data, content, out)
}

// plan decides whether data is the recorded base. It returns the content
// to publish (r.Content plus carried foreign blocks) or a refusal reason.
func (w *Writer) plan(r Rendered, form MarkerForm, data []byte) ([]byte, string, error) {
	e, managed := w.next[r.Path]
	switch {
	case !managed && !w.hadPrior:
		return nil, ReasonNoManifest, nil
	case !managed || e.GeneratorID != r.GeneratorID:
		return nil, ReasonUnmanagedFile, nil
	}
	reason, spans := verifyBase(data, form, e)
	if reason != "" {
		return nil, reason, nil
	}
	content, err := carryForeign(r, form, e, data, spans)
	return content, "", err
}

// verifyBase runs the three base checks in order and names the first that
// fails; spans are the block spans when it returns "".
func verifyBase(data []byte, form MarkerForm, e Entry) (string, []span) {
	spans, err := scanBlocks(data, form, e.knownIDs())
	switch {
	case err != nil:
		return ReasonMangledMarker, nil
	case blocksEdited(bodiesOf(data, spans), e):
		return ReasonBlockEdited, nil
	case baseEdited(data, spans, e):
		return ReasonOutsideEdited, nil
	}
	return "", spans
}

// carryForeign appends the on-disk blocks recorded under another
// generator to r.Content, unchanged, after their hashes verified.
func carryForeign(r Rendered, form MarkerForm, e Entry, data []byte, spans []span) ([]byte, error) {
	content := append([]byte(nil), r.Content...)
	for _, b := range e.Blocks {
		if b.GeneratorID == r.GeneratorID {
			continue
		}
		for _, sp := range spans {
			if sp.id == b.ID {
				content = append(lfTerminated(content), WrapBlock(form, b.ID, data[sp.bodyStart:sp.bodyEnd])...)
			}
		}
	}
	if _, err := scanBlocks(content, form, nil); err != nil {
		return nil, cascade.Wrapf(cascade.KindInvalidInput, err, "generate: %s collides with a block of another generator", r.Path)
	}
	return content, nil
}

// owners maps each recorded block id to its generator.
func owners(e Entry) map[string]string {
	m := make(map[string]string, len(e.Blocks))
	for _, b := range e.Blocks {
		m[b.ID] = b.GeneratorID
	}
	return m
}
